Hylics 2: Implement new game
ArchipelagoMW/Archipelago pull request #1058
Opened 2022-09-26 22:47 UTC by TRPG0

## What is this fixing or adding?
Hylics 2 as a new Archipelago randomizer game.

## How was this tested?
Many private tests and/or solo runs plus a couple of public tests in the discord server. I plan to do public beta testing more often now that I've finished adding extra features.

![20220926163445_1](https://user-images.githubusercontent.com/80716066/192392607-531076c9-3f13-46a9-be7a-6517d3146d31.jpg)

2022-10-01 17:34 UTC, PoryGone requested changes
Did a light readthrough, mostly looks good. Just picked out a few instances of something that needs fixing.

2022-10-01 17:34 UTC, PoryGone commented on worlds/hylics2/__init__.py
> +                tv = random.choice(tvs)
```suggestion
                tv = self.world.random.choice(tvs)
```

2022-10-01 17:34 UTC, PoryGone commented on worlds/hylics2/__init__.py
> +                    tv = random.choice(tvs)
```suggestion
                    tv = self.world.random.choice(tvs)
```

2022-10-01 17:34 UTC, PoryGone commented on worlds/hylics2/__init__.py
> +                gest = random.choice(gestures)
```suggestion
                gest = self.world.random.choice(gestures)
```

2022-10-01 17:34 UTC, PoryGone commented on worlds/hylics2/__init__.py
> +                tv = random.choice(tvs)
```suggestion
                tv = self.world.random.choice(tvs)
```

2022-10-13 05:50 UTC, Berserker66 approved these changes

2022-10-13 05:51 UTC, merged