move output file name logic into core
ArchipelagoMW/Archipelago pull request #1066
Opened 2022-09-29 16:11 UTC by beauxq

I see the same logic with small variations in each different world implementation. It seems to me, it would be better in the core to keep it consistent.

## What is this fixing or adding?

move output file name logic into core

## How was this tested?

 - unit tests
 - generate a 2-player super metroid seed

Maybe a few people could test generate for other rom games.

2022-09-29 18:19 UTC, Berserker66 commented on BaseClasses.py
> +    # REVIEW: Change this to `_get_file_safe_player_name` ?
can probably remain a public API in case someone has a use for it.

2022-09-29 21:52 UTC, black-sliver requested changes
Suggesting quotes as per https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/style.md#python-code where touched

2022-09-29 21:52 UTC, black-sliver commented on worlds/alttp/__init__.py
> +            rompath = os.path.join(output_directory, f'{self.world.get_out_file_name_base(self.player)}.sfc')
```suggestion
            rompath = os.path.join(output_directory, f"{self.world.get_out_file_name_base(self.player)}.sfc")
```

2022-09-29 22:34 UTC, black-sliver commented
The json name change crashes here in webhost:
https://github.com/ArchipelagoMW/Archipelago/blob/36eb80c725f844fa62101a40795ed7570494d281/WebHostLib/upload.py#L83-L84

Pinging @Marechal-L for naming suggestions

2022-09-29 23:48 UTC, beauxq commented
> The json name change crashes here in webhost

I mentioned small variations. One of the variations I saw was hyphen `-` instead of underscore `_`.

I wonder if this just needs `split('-'` to change to `split('_'` ?

2022-09-30 00:10 UTC, beauxq commented
It looks like DS3 was not using the filename-safe version of the player name, which means it might have crashed (under the current system) if someone used certain characters in their name?

If we need the actual player name, rather than the one that has been made safe for file names, I think that should probably come from inside the json data, rather than from the filename.

2022-09-30 06:58 UTC, black-sliver commented
> I wonder if this just needs split('-' to change to split('_' ?

This will break the transition from 0.3.5 to 0.3.6, which is *probably* not that much of a deal (besides not getting a good error message), but I don't know if that change would require changes elsewhere (i.e. in the game documentation), which is why i pinged the world maintainer.

>  It looks like DS3 was not using the filename-safe version of the player name, which means it might have crashed (under the current system) if someone used certain characters in their name?
> And what if someone puts a hyphen in their name?

split(..., 3) stops splitting at the player_name, so that's no issue. Unsafe player_name however is

> If we need the actual player name, rather than the one that has been made safe for file names, I think that should probably come from inside the json data, rather than from the filename.

Yeah, i think it should first read multidata and set up the slots, then iterate over stuff and set up the downloads (validating game, not setting game).

As a side note, we are not super happy with using *.json. The preferred thing would be to provide a APContainer for all games where feasible, but adding unzip to all game clients is not easy to do. I think APContainer support could be part of apclientpp, but I want to keep that header-only to avoid the dependency mess.

2022-09-30 09:20 UTC, Marechal-L commented
I worked on a feature to remove the output file and use the slot_data instead. I will open the pull-request this weekend.
So feel free to fix it as simple as possible

2022-09-30 13:37 UTC, beauxq commented
I reverted the change to DS3 output file name, so that issue can be handled in a different pull request, and this doesn't break it more.

2022-10-02 14:52 UTC, black-sliver approved these changes

2022-10-02 14:53 UTC, merged