Docs: Polished Trigger and Plando guides
ArchipelagoMW/Archipelago pull request #1080
Opened 2022-10-07 15:20 UTC by recklesscoder

## What is this fixing or adding?
A pass of polish for the trigger and plando guides.

The changes in roughly descending order of severity are:
- Hopefully improved the clarity of the trigger part explanation
- Fixed the last trigger example (indents were messed up)
- Minor nomenclature changes, that someone should review in context
    - "root category" -> "category"
    - "root option" -> "category"
    - "imaginary names" -> "imaginary values"
- Moved some links to be inline
- Added commas
- Fixed some capitalization
- Misc homogenization

2022-10-09 18:34 UTC, SoldierofOrder requested changes
Coupla little commas. The changes look good otherwise. :)

2022-10-09 18:34 UTC, SoldierofOrder commented on worlds/generic/docs/plando_en.md
> +On the website plando will already be enabled. If you will be generating the game locally, plando features must be
```suggestion
On the website, plando will already be enabled. If you will be generating the game locally, plando features must be
```

2022-10-09 18:34 UTC, SoldierofOrder commented on worlds/generic/docs/plando_en.md
> +4. This block has an 80% chance of occurring and when it does, it will place all but 1 of the items randomly among the
```suggestion
4. This block has an 80% chance of occurring, and when it does, it will place all but 1 of the items randomly among the
```

2022-10-09 18:34 UTC, SoldierofOrder commented on worlds/generic/docs/plando_en.md
> +1. These connections are decoupled, so going into the Lake Hylia Cave Shop will take you to the inside of Cave 45 and
```suggestion
1. These connections are decoupled, so going into the Lake Hylia Cave Shop will take you to the inside of Cave 45, and
```

2022-10-09 18:34 UTC, SoldierofOrder commented on worlds/generic/docs/plando_en.md
> +   when you leave the interior you will exit to the Cave 45 ledge. Going into the Cave 45 entrance will then take you to
```suggestion
   when you leave the interior, you will exit to the Cave 45 ledge. Going into the Cave 45 entrance will then take you to
```

2022-10-09 18:34 UTC, SoldierofOrder commented on worlds/generic/docs/plando_en.md
> +   you to their locations as normal but leaving Old Man Cave will exit at Agahnim's Tower.
```suggestion
   you to their locations as normal, but leaving Old Man Cave will exit at Agahnim's Tower.
```

2022-10-10 00:15 UTC, alwaysintreble approved these changes
This is all just minor grammar and fixing that indentation in the SoE section that broke at some point which I noticed recently and hadn't gotten around to fixing yet so all of it LGTM after soldieroforder's comments get merged in

2022-10-10 01:25 UTC, recklesscoder commented
I found some more crimes against grammar and particularly poorly worded sentences I somehow glossed over the first time.

2022-10-10 07:09 UTC, black-sliver approved these changes
Happy little commas =)

Thanks!

2022-10-10 07:10 UTC, merged