WebHost: Fixed scrolling to anchors
ArchipelagoMW/Archipelago pull request #1085
Opened 2022-10-08 13:32 UTC by recklesscoder

## What is this fixing?
Anchors are used to mark a specific spot in a longer page as part of the URL. Consider the following URL:

> [https://archipelago.gg/faq/en/#what-happens-if-a-person-has-to-leave-early?](https://archipelago.gg/faq/en/#what-happens-if-a-person-has-to-leave-early?)

Opening the page using that URL should automatically jump to the section specified by the anchor. However, currently sometimes it doesn't work, and when it does, the start of the section is obscured by the clouds of the header. The same problem occurs when clicking on a heading, which updates the anchor in your URL bar and scrolls it so far to the top that it is obscured by the clouds.

This PR fixes these problems. It also modernizes the code a little bit (for-each loops, `window.location.hash` instead of character juggling with `window.location.href`).

## How was this tested?
I ran a local web host and tested opening pages with anchors, clicking on headings, editing the anchor in the URL bar (which jumps to an anchor without reloading the page), and pressing the back/forward buttons on my mouse. Tested in Firefox, Chrome and Edge.

Here are some URLs for you to try:
- [http://localhost/faq/en/#what-happens-if-a-person-has-to-leave-early?](http://localhost/faq/en/#what-happens-if-a-person-has-to-leave-early?)
- http://localhost/glossary/en/#logic
- http://localhost/tutorial/Super%20Mario%20World/setup/en#bizhawk
- http://localhost/tutorial/Archipelago/advanced_settings/en#random-numbers
- [http://localhost/games/Super%20Mario%20World/info/en#what-does-randomization-do-to-this-game?](http://localhost/games/Super%20Mario%20World/info/en#what-does-randomization-do-to-this-game?)

## Known Issues
- In Firefox only, and only when opening a tab with an anchor in the background, the browser ignores the scroll command and shows the top of the page when the tab is activated. I am currently out of ideas on why this happens and what a good workaround would be.

2022-10-08 21:10 UTC, LegendaryLinux requested changes

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/gameInfo.js
> +            const headerId = header.innerText.replaceAll(' ', '-').toLowerCase()
See above comment about global regex replacement.
Use `.replace(/\s+/g, '-')`

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/gameInfo.js
> +                window.location.hash = '#' + headerId;
Prefer string interpolation rather than concatenation.
```
window.location.hash = `#${headerId}`;
```

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/glossary.js
> +                window.location.hash = '#' + headerId;
Prefer string interpolation rather than concatenation.

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/glossary.js
> +            const headerId = header.innerText.replaceAll(' ', '-').toLowerCase()
See above comment about global regex replacements.

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/tutorial.js
> +                window.location.hash = '#' + headerId;
Prefer string interpolation rather than concatenation.

2022-10-08 21:10 UTC, LegendaryLinux commented on WebHostLib/static/assets/tutorial.js
> +            const headerId = header.innerText.replaceAll(' ', '-').toLowerCase()
See above comment about global regex replacements.

2022-10-09 09:59 UTC, recklesscoder commented on WebHostLib/static/assets/faq.js
> +        document.fonts.ready.finally(() => {
I didn't either, but it was the perfect solution for the variable layout delay caused by some browsers deciding to re-fetch fonts after the rendered markdown is inserted. Chrome did the re-fetch very consistently, Firefox only occasionally.
Technically, we would probably want to pre-load those fonts even before fetching the markdown, but that felt out of scope.

2022-10-09 10:08 UTC, recklesscoder commented
While we're on the subject of fixing up the anchor strings, what do you think about doing something like this?:
```javascript
const headerId = header.innerText.replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-+|-+$/g, '').toLowerCase();
```
(This replaces everything that is not a letter or a number with dashes, then trims dashes off the front and back.)

As for motivation:
I noticed that some places (like GitHub comments) try to be smart when processing URLs and don't deem a trailing question mark part of the URL, like this: https://archipelago.gg/faq/en/#what-happens-if-a-person-has-to-leave-early?
(In the first post I manually marked up the links to include the question mark.)

2022-10-11 03:21 UTC, LegendaryLinux commented
I honestly think that might be a bit of over-engineering. It wouldn't be the markdown engine analyzing the content of the `h1`, it'd be the JS, which handles it properly.

2022-10-11 03:23 UTC, LegendaryLinux approved these changes

2022-10-14 21:09 UTC, merged