Subnautica: Rename location check (id 33029)
ArchipelagoMW/Archipelago pull request #1120
Opened 2022-10-20 05:30 UTC by Klenoa

## What is this fixing or adding?
Updates the name of  'Grassy Plateaus West Wreck - Databox' to  'Grassy Plateaus Southwest Wreck - Databox'. This helps distinguish between the two distinct wrecks within the western grassy plateaus area and brings the name into alignment with the [Poptracker Subnautica package](https://github.com/lurch9229/SubnauticaAP_maptracker_lurch9229).

## How was this tested?
I did not perform any testing of this change, since at this time I am unsure how to build the Archipelago project from source and this was a relatively simple change to a JSON file name. If desired, I can learn how to build the Archipelago source and verify this JSON change works as intended.

2022-10-28 22:01 UTC, ThePhar commented
Changing a location name will also require an increment of the data_version in the __init__.py file.

2022-11-01 06:24 UTC, Berserker66 requested changes
Can confirm it's a different wreck, but will need a datapackage bumb here and a json update in the mod.

2022-11-07 01:32 UTC, Klenoa commented
Thank you both for the feedback! Per your request, I have updated the data_version and have created a separate PR for the poptracker, [which can be found here](https://github.com/lurch9229/SubnauticaAP_maptracker_lurch9229/pull/2).

@Berserker66 I'm not entirely sure if those changes in the poptracker were what you were requesting (I believe the Crater.json file was correct already, barring the minor discrepancies in naming), so if I missed/overlooked something or misunderstood your request, let me know!

2023-02-26 08:47 UTC, Berserker66 approved these changes

2023-02-26 08:48 UTC, merged