add new translation for minecraft setup in french
ArchipelagoMW/Archipelago pull request #1410
Opened 2023-01-24 11:46 UTC by TheLynk

Please format your title with what portion of the project this pull request is
targeting and what it's changing.

ex. "MyGame4: implement new game" or "Docs: add new guide for customizing MyGame3"

## What is this fixing or adding?
Adding new translation for minecraft setup in french

## How was this tested?
in local web server

## If this makes graphical changes, please attach screenshots.
no graphical changes

2023-01-25 07:49 UTC, Berserker66 commented
@KonoTyran and @espeon65536 
My recommendation for review is to run it back to english through a translation and see if it looks at least mostly ok. Unless one of you is capable of French of course.

2023-01-26 20:35 UTC, espeon65536 commented
I do not understand French, but I am suspicious of the translation quality because the example YAML provided in the OoT tutorial (which needs to be gotten rid of anyway, tbh) is also translated into French. This will obviously not work for generation, which a human translating should recognize; this makes me suspect the entire thing was done by machine translation.

2023-01-27 09:49 UTC, TheLynk commented
I did use translation software but I reformulated the sentences that had no no or badly translated while keeping the information

2023-01-27 11:25 UTC, TheLynk commented
So I just finished making the necessary changes for the example in the YAML for OOT

2023-02-19 16:34 UTC, Marechal-L commented on worlds/oot/docs/setup_fr.md
> +  0: 0 # Choisissez un nombre inférieur si cela ne vous dérange pas d'avoir un multimonde plus long, ou si vous pouvez glitch / séquences autour d'éléments manquants.
```suggestion
  0: 0 # Choisissez un nombre inférieur si cela ne vous dérange pas d'avoir un multimonde plus long, ou si vous pouvez glitch / faire du hors logique.
```

2023-02-19 16:36 UTC, Marechal-L commented
I suggest to make this one last change to make it mergeable.
Thanks from the French players community :)

2023-02-21 09:55 UTC, TheLynk commented
> I suggest to make this one last change to make it mergeable. Thanks from the French players community :)

to welcome and update my git for to make it mergeable

2023-02-23 08:42 UTC, black-sliver requested changes
I don't speak french, but I believe all requested changes were made and two people read it.

If something is or becomes horribly wrong or outdated content-wise, we'll hopefully get a bug report for it.

The only thing that is missing now is adding it to the worlds' tutorials
[here](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/oot/__init__.py#L88) and [here](https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/minecraft/__init__.py#L50) (scroll up a bit to see what espanol does and copy that).

2023-02-24 03:08 UTC, TheLynk commented
I made the changes that you required

2023-02-27 21:34 UTC, black-sliver requested changes
Found two formatting issues

2023-02-27 21:34 UTC, black-sliver commented on worlds/minecraft/docs/minecraft_fr.md
> +-Minecraft Java Edition à partir de
```suggestion
- Minecraft Java Edition à partir de
```

2023-02-27 21:34 UTC, black-sliver commented on worlds/oot/docs/setup_fr.md
> +le serveur utilise un mot de passe, saisissez dans le champ de texte inférieur `/connect <adresse> :<port> [mot de passe]`)
```suggestion
le serveur utilise un mot de passe, saisissez dans le champ de texte inférieur `/connect <adresse>:<port> [mot de passe]`)
```

2023-02-27 22:12 UTC, black-sliver approved these changes
Thanks!

2023-02-27 22:17 UTC, merged