Timespinner: many new stuffs
ArchipelagoMW/Archipelago pull request #1433
Opened 2023-02-04 15:25 UTC by Jarno458

## What is this fixing or adding?
(Only listing the AP changes here, not client changes)
* New Flags:
  * [Dad Percent]: "The win condition is beating the boss of Emperor's Tower"
  * [Rising Tides]: "Random area's are flooded"
  * [Unchained Keys]: "Start with Twin Pyramid Key, which does not give free warp; warp items for Past, Present, (and ??? with Enter Sandman) can be found"
  * [Trapped Chests]: "Items can be traps. Toggle available traps in the 'Traps' settings"
    * Specific traps can be turned on or off

New yaml for these options:
```yaml
  DadPercent: random #Toggle
  RisingTides: true #Toggle
  RisingTidesOverrides:
    Xarion: # Regions can be: CastleBasement, Xarion, Maw, AncientPyramidShaft, Sandman, CastleMoat, CastleCourtyard, LakeDesolation, LakeSerene
      Dry: 50
      Flooded: 450
  UnchainedKeys: random #Toggle
  TrapChance: 100 #Range 0 - 100
  Traps:
    - 'Bee Trap' # Can bee: 'Meteor Sparrow Trap', 'Poison Trap', 'Chaos Trap', 'Neurotoxin Trap', 'Bee Trap'
```

## How was this tested?
Using AP world available in the timespinner channel in discord channel for the last two weeks
Also many generation tests, to find generation issues
Tracker changes where tested through a local webhost only
(the client side of the changes where tested and developed over past two months as a beta)

2023-02-16 20:11 UTC, alwaysintreble reviewed
Looks good other than a random change I don't understand. Would be nice if you added some tests for the new logic stuff -hint hint-

2023-02-17 07:52 UTC, Berserker66 commented on setup.py
> +    "Timespinner"
```suggestion
    "Timespinner",
```

2023-02-18 15:43 UTC, black-sliver requested changes
Tracker requires https://github.com/ArchipelagoMW/Archipelago/pull/1453 but seems to work fine with it.

Found a couple of typos and some inconsistencies. I don't really care where you put your braces and brackets and white spaces, but it should be consistent.

Also please make sure the changes in WebHostLib match the corresponding sections from style.md. (You added a lot of spaces in front of `{` in the css)

(Looks like  #1034 will pass after merging this)

2023-02-18 15:43 UTC, black-sliver commented on worlds/timespinner/__init__.py
> +            if(self.precalculated_weights.flood_basement):
Please consider removing the `()` from the ifs here

2023-02-18 15:43 UTC, black-sliver commented on worlds/timespinner/__init__.py
> +        if (self.multiworld.random.random() < (trap_chance / 100) and enabled_traps):
```suggestion
        if self.multiworld.random.random() < (trap_chance / 100) and enabled_traps:
```

2023-02-18 15:43 UTC, black-sliver commented on worlds/timespinner/__init__.py
> +                (self.precalculated_weights.present_key_unlock))
Also the way you pass in the strings looks wrong:
Having `(something)` looks like it should be `(something,)` (i.e. a tuple). If you explicitly just want `something` (i.e. a str), then remove the `()` - sounds like a small thing, but having to figure out what a pair of `()` does makes reviewing a bit harder.

2023-02-19 13:57 UTC, Jarno458 commented
> Tracker requires #1453 but seems to work fine with it.
WDYM requires? this was tested and developed without any addition branches, just master + my changes?

2023-02-19 18:22 UTC, black-sliver commented
> > Tracker requires #1453 but seems to work fine with it.
> > @black-sliver WDYM requires? this was tested and developed without any addition branches, just master + my changes?

Tracker is currently broken on main, not your fault, so when you merged main, it broke on your branch as well. Just wanted to point that out if anyone else wants to test.

2023-02-19 18:30 UTC, black-sliver approved these changes

2023-02-19 20:22 UTC, merged