LADX: BizHawk connector / RetroArch API faker
ArchipelagoMW/Archipelago pull request #1579
Opened 2023-03-23 22:21 UTC by wbsch

This is based on #1578, the actual change is just adding connector_ladx.lua.

## What is this fixing or adding?
This Lua script makes the LADX Archipelago client work without any other changes once the script is loaded in BizHawk.

The approach taken here is to clone the relevant parts of the RetroArch connect API as used by Archipelago's LADX client.

For comments, frustrations, and general RetroArch UDP API hatred please refer to the code comments.

## How was this tested?
Several games were started, but none finished for lack of motivation.

The same script was used for a full LADXR seed and the MagPie autotracker, which is very close (as in, has been mostly copied) to what the Archipelago LADX client does.

More testing is very welcome, but no problems were encountered so far.

2023-03-25 19:02 UTC, t3hf1gm3nt commented
I've ran a quick test and can verify it worked for the few checks I quickly did.
Intend to run a full seed with this later to further verify

2023-03-28 18:29 UTC, zig-for requested changes
Figment and Brooty have both run this with no issues. I don't have a problem with this going in.

Changes requested:
1. Rebase onto `ap/main` unless the parent is going to merge soon
2. Add to the README for LADX

2023-03-28 18:43 UTC, wbsch commented
> 1. Rebase onto `ap/main` unless the parent is going to merge soon

The question is, do I add a sixth folder with the sixth copy of socket.lua and core.dll, or do I put the LADX connector into the data/lua base folder and hope the other pull request gets merged at some point?

> 2. Add to the README for LADX

Docs already exist in this PR, unless this is not to your liking:
https://github.com/ArchipelagoMW/Archipelago/pull/1579/files#diff-fb2a9736d50c13943834a06fe0f3a44aabc9263ef6112dd6ca568154e1fd8833

2023-03-30 13:32 UTC, Berserker66 approved these changes

2023-03-30 13:55 UTC, merged