Add Raft to Archipelago
ArchipelagoMW/Archipelago pull request #174
Opened 2021-12-30 01:36 UTC by SunnyBat

Add Raft to Archipelago

- Locations include notes, blueprints, Research Table, and specific quests
- Items include craftable non-decoration items and frequencies
- Optional resource packs and duplicate items included to even out amount of locations vs items
- Tests are all passing (no non-autogenerated tests added at this time)
- No custom tracker has been added at this time

2021-12-30 05:04 UTC, Ijwu commented
Thanks for this. We're looking everything over and waiting for the chance to play a beta game. Let us know when multiple players may play in the same session, that would make things very interesting!

2021-12-30 08:20 UTC, JarnoWesthof requested changes

2021-12-30 08:20 UTC, JarnoWesthof commented on worlds/raft/Rules.py
> +    def paddleboard_mode_enabled(self, player):
logic mixins are all loaded together on the collection state object, therefor its highly recommended to make custom logicMixin methods have a prefix of the game like _raft_

2021-12-30 08:20 UTC, JarnoWesthof commented on WebHostLib/static/assets/tutorial/tutorials.json
> +  },,
double ,

2022-01-21 21:41 UTC, merged

2022-01-21 21:41 UTC, Berserker66 commented
Thank you!