LADX: Add --nomagpie argument for disabling magpie bridge
ArchipelagoMW/Archipelago pull request #1788
Opened 2023-05-02 15:30 UTC by Cybrou

## What is this fixing or adding?
It adds an command line argument --nomagpie to LinksAwakeningClient which allows to disable the embed magpie bridge.
It allows to use an other autotracking method for magpie or simply to prevent the connection attempts to the port 17026 if you have something else that use it.

## How was this tested?
I played a partial seed with and without, I got the expected result (no magpie connection with the argument, functionnal autotracking without it) 

## If this makes graphical changes, please attach screenshots.

Without the --nomagpie switch:
![image](https://user-images.githubusercontent.com/106977036/235712890-4de21fd7-9211-40fb-b56c-a45520c05b9f.png)

With the --nomagpie switch:
![image](https://user-images.githubusercontent.com/106977036/235713123-bfe19908-8ad3-4205-a19c-5bf3eb8a5984.png)

2023-05-04 02:51 UTC, Berserker66 commented
@zig-for

2023-05-06 17:26 UTC, zig-for commented on LinksAwakeningClient.py
> +    parser.add_argument("--nomagpie", default=False, action='store_true', help="Disable magpie bridge")
`--no-magpie` please

2023-05-06 17:30 UTC, zig-for requested changes
LGTM other than swapping the bool (bool variables should almost never start with "no" - just invert them.

2023-05-06 17:30 UTC, zig-for commented on LinksAwakeningClient.py
> +    parser.add_argument("--nomagpie", default=False, action='store_true', help="Disable magpie bridge")
Even better
 `   parser.add_argument("--no-magpie", dest='magpie", default=False, action='store_false`, help="Disable magpie bridge")`
then pass `args.magpie` to the context.

2023-05-06 18:31 UTC, Cybrou commented
Done ! That dest argument is handy.

2023-05-20 13:30 UTC, Berserker66 approved these changes

2023-05-20 13:30 UTC, merged