WebHost: Fix special-range value setting to `custom` when randomization is toggled off
ArchipelagoMW/Archipelago pull request #1856
Opened 2023-06-02 03:40 UTC by ThePhar

## What is this fixing or adding?
Discord Bug Report: https://discord.com/channels/731205301247803413/1113657616397246544

> **Exempt-Medic**: If you go to any game's settings page and set progression balancing to Custom and then click the die to randomize it and then click the die again to unrandomize it, the progression balancing gets given a value of "custom" and attempting to generate gives the error:
> > Something went wrong and your game could not be generated. {'player': 'Failed to generate mystery in player: Error generating option progression_balancing in The Witness'}

---

When toggling randomization off on any "Special Range" type option on a player settings page, it would update the "value" of the option to: `custom`, causing a generation issue as its not a valid option.

This fixes that issue by preventing an unneeded update to game settings when toggled.

## How was this tested?
Ran WebHost and tested value set in localStorage is valid.

Before:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/ebff02ae-2e0d-4a77-bf58-297cb355b176)
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/397b20b6-9b75-4cd5-ab3d-1c01f7606421)

After:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/d309aefc-6c79-4ed5-9557-fcdf98dc18c4)
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/73d8ead3-4be2-42e8-9526-17a09f01e97d)

## If this makes graphical changes, please attach screenshots.
See above.

2023-06-02 17:54 UTC, Berserker66 approved these changes

2023-06-03 00:41 UTC, LegendaryLinux requested changes

2023-06-03 00:41 UTC, LegendaryLinux commented on WebHostLib/static/assets/player-settings.js
> +const toggleRandomize = (event, inputElement, optionalSelectElement) => {
It is preferable to use default values of null for optional arguments. Consider changing this to:
```js
const toggleRandomize = (event, inputElement, selectElement = null) =>
```

2023-06-23 02:11 UTC, LegendaryLinux approved these changes

2023-06-23 02:12 UTC, merged