SM: 0.4.1 fixes
ArchipelagoMW/Archipelago pull request #1859
Opened 2023-06-04 20:17 UTC by lordlou

## What is this fixing or adding?
fixed broken Item links (https://discord.com/channels/731205301247803413/1110346952442400778/1110346952442400778)
fixed `KeyError: Flyway Right 0` exceptions cause by missing collection ordering of the loc/Items list. Also added a missing force disable of Escape Rando if no escape solution can be found. (https://discord.com/channels/731205301247803413/909599727341928538/1109248603429535834)

## How was this tested?
In both cases, generations was always failing when using the reported YAML. They now succeed with the fixed applied. I also tested the YAML with a second copy of itself and 2 more different games.

2023-06-27 22:14 UTC, ThePhar requested changes
Some concerns I have about some of the doc comments in Objectives is they reference the internal name of the option, but on the WebHost they won't appear so it will look off.

Example:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/a146ee6e-f813-435b-91a3-a4fbb7b79867)

This also fails to generate with default settings on WebHost as "random" is not a valid default for an `OptionSet` type Option:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/14b70041-3f84-49e2-b407-3f9329af75c2)

2023-06-27 23:06 UTC, KitsuneZeta commented
Independently of ThePhar's review, it was discovered that these changes introduced a bug where not all items get replaced with the shuffled-in items, which results in various checks not getting counted and vanilla items where an AP item is expected to be. This bug also affects Plando'd items. The specific commit that appears to be the cause of this is [a7b0c16](https://github.com/ArchipelagoMW/Archipelago/pull/1859/commits/a7b0c164eacb72747c342e6123c8b7390a504e72), as undoing that commit alone fixes the issue. These findings have already been reported to the maintainer separately.

2023-06-29 04:22 UTC, lordlou commented on worlds/sm/Options.py
> +    display_name = "randomize custom objectives"
Fixed with 990381068c0d6a8936781a01e9c86d333d54dcf3.

2023-06-29 04:24 UTC, lordlou commented on worlds/sm/Options.py
> +    "nbObjective": ObjectiveRandomCount,
It was to reflect VARIA's corresponding variables but it shouldnt have been the case here. Fixed with 990381068c0d6a8936781a01e9c86d333d54dcf3.

2023-06-29 04:25 UTC, lordlou commented
> Independently of ThePhar's review, it was discovered that these changes introduced a bug where not all items get replaced with the shuffled-in items, which results in various checks not getting counted and vanilla items where an AP item is expected to be. This bug also affects Plando'd items. The specific commit that appears to be the cause of this is [a7b0c16](https://github.com/ArchipelagoMW/Archipelago/pull/1859/commits/a7b0c164eacb72747c342e6123c8b7390a504e72), as undoing that commit alone fixes the issue. These findings have already been reported to the maintainer separately.

Fixed with da36b61ac87b67815d6bd5e5d061c041d4734149.

2023-06-29 12:51 UTC, merged