WebHost: unify references to options
ArchipelagoMW/Archipelago pull request #2037
Opened 2023-07-26 22:22 UTC by alwaysintreble

## What is this fixing or adding?
Unify references to options in the webhost as options, instead of using options and settings interchangeably.

## How was this tested?
Running webhost and viewing the changes. Weighted options page is currently broken so putting in draft for now.

## If this makes graphical changes, please attach screenshots.
![Screenshot_49](https://github.com/ArchipelagoMW/Archipelago/assets/13184667/6c6ea8d9-bb6d-4b25-9489-300d68f0e6d5)
![Screenshot_51](https://github.com/ArchipelagoMW/Archipelago/assets/13184667/55dd7bd9-e4d1-4789-bf6c-dedfda0efdd5)
![Screenshot_52](https://github.com/ArchipelagoMW/Archipelago/assets/13184667/a8b08328-a321-46b9-b949-aa6c16776bd3)

2023-07-26 23:29 UTC, MrRedstone54 commented
On the third image it shows "download a options file." This should be, "download an options file". Since this draft is about language, might as well make sure the grammar is correct.

2023-07-30 20:28 UTC, alwaysintreble commented
@LegendaryLinux

2023-08-12 23:56 UTC, LegendaryLinux commented
Semantically there is a difference between a setting and an option. A setting has both a name and a set of options.

I also don't want to change the title of the pages away from "Player Settings" and "Weighted Settings."

In your first image, the only inconsistency is the header "Game Options", which should be changed to "Game Settings." The rest is correct as written.

2023-08-12 23:59 UTC, LegendaryLinux requested changes
See my above comment.

2023-08-13 03:20 UTC, alwaysintreble commented
> Semantically there is a difference between a setting and an option. A setting has both a name and a set of options.
> 
> I also don't want to change the title of the pages away from "Player Settings" and "Weighted Settings."
> 
> In your first image, the only inconsistency is the header "Game Options", which should be changed to "Game Settings." The rest is correct as written.

So, semantically, I agree. I should've more clearly outlined the goal/reasoning in the original post so that's on me. Previously, in the API we've been kind of using settings and options interchangeably, but as of https://github.com/ArchipelagoMW/Archipelago/commit/827444f5a4e065bc310c889892580eb1f97c73cb this is no longer the case. We now have a clear cut line in the actual Archipelago API on wh at an "option" and a "setting" are, used to define 2 separate interactions, where an option is a player submitted choice for their world, and a setting is the host configured choices for the multiworld, and the local settings used to configure their Archipelago installation (ROM paths etc). Primary goal of this PR is to unify these terms so that any references to options are called options, and references to settings are settings. I'm open to compromise if you still believe it, but context is important here.

2023-08-13 14:31 UTC, black-sliver reviewed
The change to use consistent language is very welcome from a my point of view. When people talk about "player options" it should be clear that the game's option api will be used. When people talk about "game settings" it should be clear that we talk about the game's settings api/host.yaml.

"Player settings" is unclear in that regard.

2023-08-13 14:31 UTC, black-sliver commented on WebHostLib/misc.py
> +    return render_template(f"player-options.html", game=game, theme=get_world_theme(game))
I would like to see a flask.redirect from the old url to the new one with code 301 Moved Permanently for a version or two, so link in browser history get updated. (I have not checked if the site map "breaks" doing that)

2023-09-11 21:10 UTC, LegendaryLinux approved these changes
Finally found time to go through this. Looks okay to me.

2023-10-21 11:38 UTC, black-sliver requested changes

2023-10-21 11:38 UTC, black-sliver commented on WebHostLib/misc.py
> +    return redirect("/weighted-options", 301)
I think this is how it's supposed to be done:
```suggestion
    return redirect(url_for('player_options', game=game), 301)
```

2023-10-22 09:56 UTC, black-sliver commented
Hm, we use `"` in AP, not `'`. Can you change the changed strings? I realize that my suggestion was wrong - have been working on a different code base at the time :S

2023-10-22 10:41 UTC, alwaysintreble commented
I did `'` not because of your suggestion, but because *most* of that file uses `'`. Not all of it does though so I suppose this could go either way.

2023-10-22 10:45 UTC, black-sliver commented
I think the decision we reached a while ago was to change all touched strings from `'` to `"`, but not change strings that are not touched.

2023-10-23 23:51 UTC, black-sliver requested changes

2023-10-23 23:51 UTC, black-sliver commented on WebHostLib/misc.py
> +def route_weighted_options():
```suggestion
def weighted_settings():
```
also `@cache.cached()` should go, sadly i can't make a suggestion for this

2023-10-23 23:51 UTC, black-sliver commented on WebHostLib/misc.py
> +def route_player_options(game: str):
```suggestion
@app.route("/games/<string:game>/player-settings")
def player_settings(game: str):
```

2023-10-24 00:05 UTC, black-sliver approved these changes
Have not checked js and css changes, only py and checked the links and redirects

2023-10-24 00:20 UTC, merged