WebHost: Show error instead of 500 for unexpected files in multidata zip
ArchipelagoMW/Archipelago pull request #2260
Opened 2023-10-03 04:19 UTC by remyjette

## What is this fixing or adding?

https://discord.com/channels/731205301247803413/1158587833435574323

For some reason the Patch.py file from the AP root dir got included in that zip which resulted in a 500 error on upload.

## How was this tested?

Uploaded the zip in the above thread on main, saw 500. Applied fix, saw error message instead.

2023-10-03 17:22 UTC, remyjette commented
> How about including the name of the unexpected file in the error message?

Sure. 
![image](https://github.com/ArchipelagoMW/Archipelago/assets/2065960/7d3920cc-271d-4633-a387-c340d85c0626)

2023-10-07 16:52 UTC, black-sliver requested changes

2023-10-07 16:52 UTC, black-sliver commented on WebHostLib/upload.py
> +            except Exception:
pycharm should give you a warning for that `except` because it's too broad.
```suggestion
            except ValueError:
```

2023-10-07 16:52 UTC, black-sliver commented on WebHostLib/upload.py
> +            except Exception:
as above
```suggestion
            except ValueError:
```

2023-10-10 21:19 UTC, black-sliver approved these changes
Thanks!

2023-10-10 21:20 UTC, merged