Update faq_en.md
ArchipelagoMW/Archipelago pull request #2313
Opened 2023-10-15 07:11 UTC by eudaimonistic

Reorganizing information and adding links to some of the various guides and website pages.  Even just adding the Getting Started, Supported Games, and Server Commands links seems like a hefty upgrade.  We have good resources, we should make them obvious.

I think more can probably be done here, but I already shuffled this around a lot.  Would appreciate suggestions or feedback.

2023-10-15 21:55 UTC, kindasneaki commented
I would probably reorganize things some more. Maybe something like:
- What is a randomizer
- What is a multi-world
- What does multi-game mean
- Can I generate a single-player game with archipelago
- How do I get started
- What are some common terms I should know?
- What happens if a person has to leave early
- What happens if an item is placed somewhere it is impossible to get
- I want to add a game to the Archipelago randomizer. How do I do that?

2023-10-15 21:56 UTC, kindasneaki commented
Also I think multi world and multi game are very similar, and we might not need both?

2023-10-15 23:34 UTC, BootsinSoots commented
I think the distinction on multi-world vs multi-game adds value to someone unfamiliar with us and why we have both terms in the software description

2023-10-16 11:35 UTC, eudaimonistic commented
The way I see it, is the FAQ page is very likely a place people would land when they first get to the website.  There are _many_ entry points to learning about this platform.  Quite a few users only know about us because of a single randomizer mod, completely unaware that we're a multiworld/multigame platform.  It helps to explain the concepts separately because they might be completely foreign to new users.

2023-10-17 00:00 UTC, kindasneaki commented
That makes sense. Any opinions on reorganizing?

2023-10-17 00:02 UTC, BootsinSoots commented
I do think I like your order a little better Sneaki. Smaller concepts to more specific ones

2023-10-17 07:56 UTC, eudaimonistic commented
> That makes sense. Any opinions on reorganizing?

That organization makes way more sense.  I arranged as suggested, and elaborated a little more on single player while doing a pass.

2023-10-17 14:29 UTC, kindasneaki requested changes
Just 2 small nit picks

2023-10-17 14:29 UTC, kindasneaki commented on WebHostLib/static/assets/faq/faq_en.md
> +including multiple games, and hosting these multiworlds on the website for ease and convenience.
```suggestion
including multiple games, and hosting these multi-worlds on the website for ease and convenience.
```

2023-10-17 14:29 UTC, kindasneaki commented on WebHostLib/static/assets/faq/faq_en.md
> +software set up.  You can use that guide to learn how to generate multiworlds.  There are also basic instructions for
```suggestion
software set up.  You can use that guide to learn how to generate multi-worlds.  There are also basic instructions for
```

2023-10-17 14:58 UTC, BootsinSoots commented
I think I disagree with this, only because the word is not hyphenated on the main page of the website

2023-10-17 15:25 UTC, kindasneaki commented
it’s very inconsistent throughout the site. In this file specifically it’s all multi-world. There is another multiworld on `line 48` that I missed also

2023-10-18 06:00 UTC, eudaimonistic commented
...Imagine making commits without reading the entire chain...

Anyway, will recommit with explicitly using multiworld as a noun.

2023-10-18 06:04 UTC, eudaimonistic commented
I've chosen to keep the usage of multi-game hyphenated, because it's probably good to articulate it differently than multiworld for natural emphasis.  When reading multi-game as a hyphenated term, it implies a modification to the combined noun multiworld.  In this context, I think it works better that way.

2023-10-18 13:09 UTC, BootsinSoots commented
I think that's for the best - the main page also shows it as multi-game

2023-10-18 13:54 UTC, kindasneaki approved these changes

2023-10-21 22:30 UTC, nicholassaylor approved these changes
I like the new order that we have and the standardization of multiworld
All of the changes are reasonable and make the faq a more straightforward read

2023-10-26 04:30 UTC, eudaimonistic commented
I've reworked the section about leaving early and turned it into a basic explanation of sync/async, so as to clarify the general flow of a multiworld.  This comes up constantly in the Discord and it seems necessary to explain here.  While I can foresee more improvements being possible beyond this point, we seem to be growing fast enough to warrant pushing this through and revisiting the page at a later date if necessary.

2023-10-28 11:26 UTC, black-sliver commented
@LegendaryLinux as the original author, I think.

2023-10-28 17:56 UTC, eudaimonistic commented
Better English than mine prevails.  I approve of those changes.

2023-10-28 18:17 UTC, LegendaryLinux approved these changes

2023-10-28 18:18 UTC, merged