Pokemon Emerald: Change "settings" to "options" in docs
ArchipelagoMW/Archipelago pull request #2517
Opened 2023-11-27 00:17 UTC by Zunawe

## What is this fixing or adding?

Brings the Emerald docs in line with #2037.

## How was this tested?

Ran web host, checked pages, clicked links.

## If this makes graphical changes, please attach screenshots.

<img src="https://github.com/ArchipelagoMW/Archipelago/assets/21088150/cc0f5b53-d428-413a-9aac-0d087398ed73" />
<img src="https://github.com/ArchipelagoMW/Archipelago/assets/21088150/a9e591b4-e17b-436f-af3e-74c8e6bc11bf" />

2023-11-28 22:56 UTC, ReverM requested changes
There seems to be two instance of the word setting left in the info doc
one is at the line 31 (with a setting it can..) and the other is at line 46 (depending on your receive item message setting)

2023-11-29 02:57 UTC, ReverM approved these changes
LGTM

2023-12-07 07:37 UTC, alwaysintreble commented on worlds/pokemon_emerald/docs/en_Pokemon Emerald.md
> +- All text is instant, and with an option it can be automatically progressed by holding A
```suggestion
- All text is instant and, with an option, can be automatically progressed by holding A

2023-12-08 13:51 UTC, Exempt-Medic approved these changes
LGTM

2023-12-20 18:54 UTC, ReverM commented
I have covered the changes in https://github.com/ArchipelagoMW/Archipelago/pull/2622, maybe this PR could be closed then?

2023-12-20 19:40 UTC, Zunawe commented
This already has reviews and doesn't need to wait on the additional approvals of all other world maintainers, so I think it makes more sense to keep this one.

2023-12-21 00:22 UTC, alwaysintreble commented
This pr is also from the world maintainer so takes precedence imo

2023-12-28 12:33 UTC, black-sliver approved these changes

2023-12-28 12:33 UTC, merged