DS3: update setup guide to preserve downpatching instructions
ArchipelagoMW/Archipelago pull request #2531
Opened 2023-11-29 09:50 UTC by Br00ty

We want to preserve this on the AP site as the future of the speedsouls wiki is unknown and may disappear at any time.

## What is this fixing or adding?
This is adding a revised version of the downpatching guide from the Speedsouls Wiki for use with Archipelago.

2023-11-29 19:39 UTC, ReverM commented on worlds/dark_souls_3/docs/setup_en.md
> +1. Launch Steam (in online mode)
Small nitpick, every subsequent step seem to be ending with a period but the first one is not
```suggestion
1. Launch Steam (in online mode).
```

2023-11-29 20:09 UTC, black-sliver requested changes
The new instructions are missing step 3 from the speedsouls wiki page

2023-11-29 23:43 UTC, Br00ty commented
thank you for pointing that out, i made that fix

2023-11-30 08:29 UTC, black-sliver approved these changes

2023-11-30 08:29 UTC, merged