Hollow Knight: Break DeathLink options up and add ExtraPlatforms option.
ArchipelagoMW/Archipelago pull request #2545
Opened 2023-12-01 05:36 UTC by ThePhar

## What is this fixing or adding?
https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/issues/157 - Splits DeathLink options up to allow more configuration of behavior on death without needing to program all possible combinations in existing DeathLink option.

https://github.com/ArchipelagoMW-HollowKnight/Archipelago.HollowKnight/issues/58 - Also adds an "ExtraPlatforms" option to create additional platforms in Hallownest to make moving around easier and prevent some issues where some logic tricks because infeasible if certain actions are taken.

@BadMagic100 - Leaving in Draft until client-side can be updated and verified they work with these changes.

## How was this tested?
No logic changes were made, but verified output on WebHost. Awaiting client-side tests before pulling out of Draft state.

## If this makes graphical changes, please attach screenshots.
N/A

2023-12-01 22:48 UTC, BadMagic100 requested changes
Will work on the client side changes this weekend and update here once they are merged

2023-12-01 22:48 UTC, BadMagic100 commented on worlds/hk/Options.py
> +    """Sets if fragile charms break when you are killed by a DeathLink. All other deaths still break fragile charms.
As noted by folks on discord it's probably slightly more accurate to say something like "fragile charms will still be broken by your own deaths as usual" to cover for cases where your own deaths actually will not break the charm

2023-12-01 22:48 UTC, BadMagic100 commented on worlds/hk/Options.py
> +    """Sets whether to create a shade when you are killed by a DeathLink and how to handle your existing shade, if any.
Similar to the fragile charms setting a caveat that your own deaths will create a shade and remove any existing shade as normal would be good

2023-12-05 17:35 UTC, ThePhar commented
Personally, I don't count those as actual deaths anyway if it doesn't drop a shade. E.g. dream fights.

2023-12-06 01:05 UTC, BadMagic100 commented
A deathlink is still sent even in cases you normally wouldn't leave a shade or end steel soul. In any case I think the comment regarding shades probably still stands.

Maybe the better way to phrase it is to put somewhere that "the penalties of your own deaths inflicted on you are unmodified," either on the deathlink toggle or with respect to each optoo

2023-12-06 01:08 UTC, BadMagic100 commented
(closing this was unintentional, the mobile UI had it out for me)

2023-12-12 07:24 UTC, ThePhar commented
Made some more verbiage tweaks.

2023-12-12 07:46 UTC, BadMagic100 approved these changes

2023-12-16 22:53 UTC, Berserker66 approved these changes

2023-12-17 16:11 UTC, merged