Death Link Amnesty
ArchipelagoMW/Archipelago pull request #2646
Opened 2023-12-30 23:47 UTC by NewSoupVi

Add Death Link Amnesty

Tested:
Once again, this was more client testing than anything, with seeds with different death link & death link amnesty values

2024-01-02 00:41 UTC, Exempt-Medic requested changes
Some spelling/wording/grammar corrections. Otherwise approved, my testing of the option had it working very well

2024-01-02 00:41 UTC, Exempt-Medic commented on worlds/witness/Options.py
> +    """Amount of panel fails to allow before sending a death in Death Link.
```suggestion
    """Number of panel fails to allow before sending a death through Death Link.
```

2024-01-02 00:41 UTC, Exempt-Medic commented on worlds/witness/Options.py
> +    0 means every panel fail with send a death, 1 means every other panel fail with send a death, etc."""
```suggestion
    0 means every panel fail will send a death, 1 means every other panel fail will send a death, etc."""
```

2024-01-02 02:28 UTC, Exempt-Medic approved these changes

2024-01-16 14:23 UTC, Berserker66 approved these changes

2024-01-16 14:24 UTC, merged