The Witness: Add Obelisk Side locations to always and priority hints
ArchipelagoMW/Archipelago pull request #2665
Opened 2024-01-04 03:56 UTC by NewSoupVi

There are certain EPs in the game that are supposed to be always and priority hints if you have the audio log hints enabled.

However, their corresponding Obelisk Side locations are never hinted, because I forgor.

This adds those.
Worth noting: "Does the location exist" is already checked elsewhere, so a check for obelisk_sides being enabled is not necessary.

2024-01-04 12:50 UTC, Exempt-Medic requested changes

2024-01-04 12:50 UTC, Exempt-Medic commented on worlds/witness/hints.py
> +    if world.options.EP_difficulty > 1:
```suggestion
    if world.options.EP_difficulty != "normal":
```
I'm pretty sure this is what was intended, since `> 1` is only Eclipse

2024-01-04 12:50 UTC, Exempt-Medic commented on worlds/witness/hints.py
> +    if world.options.EP_difficulty > 1:
```suggestion
    if world.options.EP_difficulty != "normal":
```

2024-01-12 00:01 UTC, Exempt-Medic approved these changes
LGTM. Tested that the changes correctly added the expected locations as hints

2024-01-16 12:14 UTC, Berserker66 approved these changes

2024-01-16 12:14 UTC, merged