Core: migrate start_inventory_from_pool to new options API
ArchipelagoMW/Archipelago pull request #2666
Opened 2024-01-04 04:55 UTC by alwaysintreble

## What is this fixing or adding?
I'm really good at missing things

## How was this tested?

2024-01-05 00:07 UTC, ScipioWright approved these changes
Tested by adding items to start_inventory_from_pool in Tunic. It functioned as normal, except without giving warnings about getting options from multiworld being deprecated.

2024-01-11 23:28 UTC, black-sliver commented on Main.py
> +    if any(hasattr(world.worlds[player].options, "start_inventory_from_pool") for player in world.player_ids):
I think this change is not fully correct. the old code skips for `None` as well as `{}` , the new code will run for `{}`. Should probably be `any(getattr(..., ..., None) for ...)`

2024-01-14 01:36 UTC, black-sliver requested changes

2024-01-14 01:36 UTC, black-sliver commented on Main.py
> +            player: getattr(world.worlds[player], "start_inventory_from_pool", StartInventoryPool({})).value.copy()
this is missing the `.options`, so it'll always return empty. I think going forward we should maybe add optional core options to the dataclass somehow, but that's out of scope here.
```suggestion
            player: getattr(world.worlds[player].options,
                            "start_inventory_from_pool",
                            StartInventoryPool({})).value.copy()
```

2024-01-14 01:42 UTC, black-sliver approved these changes
Thanks!

2024-01-14 01:57 UTC, merged