Docs: Add Spanish Guide for Pokemon Emerald
ArchipelagoMW/Archipelago pull request #2696
Opened 2024-01-09 22:38 UTC by nachocua

## What is this fixing or adding?
Adding a Spanish guide configuration for Pokemon Emerald

## How was this tested?
Markdown online test

## If this makes graphical changes, please attach screenshots.

2024-01-10 00:09 UTC, ShinyNT requested changes
muy buena traduccion, pero ocupa algunos cambios gramaticales y de redaccion:

general:
-no se si traducir el titulo del juego sea correcto, especialmente si no se va a usar la version en español, personalmente lo dejaria simplemente como Emerald, pero no creo que sea algo grave (aunque si otra persona que hable ingles te dice que lo cambies, deberias hacerlo)
linea 1: **Guía** lleva tilde, y el segundo "de" lo cambiaria por un "para", para que suene mejor
linea 6: en vez de "inglesa" yo pondria "en inglés", suena mejor
linea 7: en vez de "superior" yo pondria "posterior" (aunque es subjetivo)
linea 14: "reincia" esta mal escrito, es reinicia
linea 15: la palabra correcta es "desconexiones"
linea 18: "click" se traduce como "clic"
linea 20: una coma despues de "limpiarlas" no vendria mal, ya que la lectura de la frase cambia con la traduccion
linea 35: "Seleccióna" no lleva tilde
linea 43: aqui cortaste la palabra Archipelago, **continúa** lleva tilde, y BizHawk esta mal escrito
linea 47: **Aun** no lleva tilde en este contexto
linea 48: la forma correcta es "en caso de que"
linea 50: **Pokémon** lleva tilde en la e, no en la o
linea 52: **Asegúrate** lleva tilde
linea 57: **reconocerá** lleva tilde, y otra vez **Pokémon** tiene mal el tilde
linea 61: **ítems** lleva tilde
linea 72: **símbolo** lleva tilde
linea 74: **vacío** lleva tilde

eso es todo lo que compete a la traduccion en si, aun te falta incorporar el codigo de referencia del tutorial en el init.py de pokemon emerald, pero vamos por parte

2024-01-10 01:09 UTC, nachocua commented
Corregido

2024-01-10 04:13 UTC, Zunawe commented
Thanks a bunch for the translation.

In `./worlds/pokemon_emerald/__init__.py`, around line 40, there must be a new `Tutorial` for this guide, just like there is for English. And it should be added to the list of tutorials.

It might look like this:
```py
class PokemonEmeraldWebWorld(WebWorld):
    """
    Webhost info for Pokemon Emerald
    """
    theme = "ocean"

    setup_en = Tutorial(
        "Multiworld Setup Guide",
        "A guide to playing Pokémon Emerald with Archipelago.",
        "English",
        "setup_en.md",
        "setup/en",
        ["Zunawe"]
    )

    setup_es = Tutorial(
        "translated text",
        "translated text",
        "Español",
        "setup_es.md",
        "setup/es",
        ["nachocua"]
    )

    tutorials = [setup_en, setup_es]
```

You can look at `worlds\minecraft\__init__.py` for an existing example.

2024-01-10 04:19 UTC, nachocua commented
Ready.

2024-01-10 06:20 UTC, ShinyNT commented
> I'm not sure why many translated pages maintain the English page title and description.

it seems like there isn't a standard for this, last time I asked in #archipelago-dev people were divided about it (and after all, the only foreign guide that uses translated titles and descriptions is the french guide for Adventure), so there wasn't a solid position (hence I haven't done it in my guides)

in any case,
```
        "translated text",
        "translated text",
```
this wasn't literal, you must translate the actual lines from the english strings
in this case, should be something like this:
```
        "Guía de configuración para Multiworld",
        "Una guía para jugar Pokémon Esmerals en Archipelago",
```

2024-01-10 17:04 UTC, nachocua commented
Done

2024-01-10 22:09 UTC, ShinyNT approved these changes
bueno, con los ultimos cambios diria que esta muy bien la traduccion, por mi parte la apruebo

si tuviera que ajustar algo, seria en el titulo, en mi opinion "para Pokémon Emerald" suena mejor que "de Pokémon Emerald", y en la linea 11 queda mejor "y cambia las siguientes" que "y haz cambio en las siguientes", pero son cosas totalmente subjetivas

buen trabajo

2024-01-10 22:14 UTC, nachocua commented
Gracias. Quieres que haga esos cambios? no tengo problema

2024-01-10 22:33 UTC, nachocua commented
Done

2024-02-29 00:48 UTC, black-sliver approved these changes
Thanks!

2024-02-29 00:54 UTC, merged