Docs: add Translate FR guide for Generic
ArchipelagoMW/Archipelago pull request #2697
Opened 2024-01-10 05:20 UTC by deoxis9001

## What is this fixing or adding?

Docs: add Translate FR guide for Generic

## How was this tested?

## If this makes graphical changes, please attach screenshots.

2024-01-10 17:50 UTC, ReverM requested changes
Deux lignes n'ont pas été traduites dans le guide de commandes.

Le guide pour macOS n'a pas été révisé puisque je ne suis pas 100% certain si le guide de base est à jour.

2024-01-10 17:50 UTC, ReverM commented on worlds/generic/docs/commands_fr.md
> +  Defaults to 10 seconds if no argument is provided.
```suggestion
  Le compte à rebours durera 10 secondes si vous tapez simplement `!countdown` sans argument.
```

2024-01-10 17:50 UTC, ReverM commented on worlds/generic/docs/commands_fr.md
> +  Defaults to 10 seconds if no argument is provided.
Pareil que plus haut.

2024-01-10 17:50 UTC, ReverM commented on worlds/generic/docs/mac_fr.md
Je ne suis pas certain à 100% que le guide de base macOS est à jour. Il faudrait alors le revérifier avant toute traduction.

2024-01-11 23:13 UTC, black-sliver commented
I think this might need consideration in UI/UX so @LegendaryLinux

2024-03-28 18:02 UTC, agilbert1412 approved these changes
My comments are all very minor.
I looked at everything except Mac, Plando and triggers, which I don't know enough to validate

2024-04-07 17:32 UTC, deoxis9001 commented
> I think this might need consideration in UI/UX so @LegendaryLinux

what's the status of mac os documentation?

2024-06-03 08:55 UTC, ThePhar requested changes
I think until we have a better UX solution for displaying titles in different languages, these should be combined like all other setup docs handle it.

Example:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/a969aed4-dd17-48f2-8bda-dd073bf1b674)

Instead of the following:
![image](https://github.com/ArchipelagoMW/Archipelago/assets/11338376/1ba13401-a782-43ed-95ea-b7e043e1a055)

2024-07-30 19:16 UTC, deoxis9001 commented
> I think until we have a better UX solution for displaying titles in different languages, these should be combined like all other setup docs handle it.
> 
> Example: ![image](https://private-user-images.githubusercontent.com/11338376/336005354-a969aed4-dd17-48f2-8bda-dd073bf1b674.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjcxMTYsIm5iZiI6MTcyMjM2NjgxNiwicGF0aCI6Ii8xMTMzODM3Ni8zMzYwMDUzNTQtYTk2OWFlZDQtZGQxNy00OGYyLThiZGEtZGQwNzNiZjFiNjc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2MTRkNmUyN2M0YTg0Y2M3NTg0MGNlN2RhMGM3YmYwYTVhYmIzMDcyOGZjN2I5Zjk5NGQyYzI4NTNmNGNhMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LAgHRKP0FTzu2QV6pjPzmU31Ct0VI9aW4nQwGFCXizs)
> 
> Instead of the following: ![image](https://private-user-images.githubusercontent.com/11338376/336005451-1ba13401-a782-43ed-95ea-b7e043e1a055.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzNjcxMTYsIm5iZiI6MTcyMjM2NjgxNiwicGF0aCI6Ii8xMTMzODM3Ni8zMzYwMDU0NTEtMWJhMTM0MDEtYTc4Mi00M2VkLTk1ZWEtYjdlMDQzZTFhMDU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDE5MTMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhNjVlZTlmZjc0YzdhODBjODIyMzMzOTU1ZDBiNzlhYTJmOGU0ZWM4ODc1MjQwNDBmNmMxMjhjZTY5YzE0NzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.B8O7wH8YhZNS7bazupzOPAC1FI5NNqgTHtsPjc9DINs)

On DLCQuest, I was told to follow the example of “Adventure”.

![image](https://github.com/user-attachments/assets/dfa89a77-9c8a-4946-b51b-fc4ff8d05519)

2024-08-21 18:56 UTC, deoxis9001 commented
I think I'll close this request if I don't get an answer.

2024-08-21 19:11 UTC, agilbert1412 commented
I'll update the tags for you, but for what it's worth, I've personally started closing my PRs if they get blocked over something minor and follow up questions are ignored.

2024-08-21 19:19 UTC, deoxis9001 commented
> I'll update the tags for you, but for what it's worth, I've personally started closing my PRs if they get blocked over something minor and follow up questions are ignored.

I'm really hesitating to close the PR and open it again on a blank PR.

2024-08-21 19:46 UTC, agilbert1412 approved these changes

2024-08-27 10:06 UTC, closed without merging