Docs: add Translate FR guide for DLCQuest
ArchipelagoMW/Archipelago pull request #2699
Opened 2024-01-10 16:48 UTC by deoxis9001

## What is this fixing or adding?

Docs: add Translate FR guide for DLCQuest

## How was this tested?

## If this makes graphical changes, please attach screenshots.

2024-01-10 18:01 UTC, ReverM requested changes
Quelques petits détails ici et là mais très bien en grande partie.

J'aime la traduction "stock" pour le mot "pool"!

2024-01-10 18:02 UTC, deoxis9001 commented on worlds/dlcquest/docs/fr_DLCQuest.md
> +Tous les DLC du jeu sont mélangés dans le stock d'objets. Les objets liés aux contrôles optionnels décrits ci-dessus sont également dans le stock
oui c'est dure de trouver une traduction pour pool

2024-01-10 18:22 UTC, deoxis9001 commented on worlds/dlcquest/docs/setup_fr.md
> +de l'Archipel : [Basic Multiworld Setup Guide](/tutorial/Archipelago/setup/en)
je sais pas pourquoi je l'ai traduit.

2024-01-10 18:24 UTC, deoxis9001 commented on worlds/dlcquest/docs/fr_DLCQuest.md
> +Les contrôles de localisation dans DLC Quest comprennent toujours
corrigé

2024-01-10 18:25 UTC, deoxis9001 commented on worlds/dlcquest/docs/fr_DLCQuest.md
> +Les DLC seront obtenus en tant que check pour le multiworld. Il existe également d'autres chèques optionnels dans DLC Quest
corrigé

2024-01-10 18:25 UTC, deoxis9001 commented on worlds/dlcquest/docs/fr_DLCQuest.md
> +## Qu'est-ce qu'un contrôle d'emplacement dans DLC Quest ?
corrigé

2024-01-10 18:26 UTC, deoxis9001 commented on worlds/dlcquest/docs/setup_fr.md
> +- Localisez le fichier "ArchipelagoConnectionInfo.json", à la racine de votre installation moddée. Vous pouvez éditer ce fichier avec n'importe quel éditeur de texte, et vous devez entrer l'adresse I
j'ai corrigé aussi

2024-01-10 19:37 UTC, axe-y commented on worlds/dlcquest/__init__.py
> +        "English",
il faudrait changer à francais

2024-01-10 19:40 UTC, deoxis9001 commented on worlds/dlcquest/__init__.py
> +        "English",
fixer

2024-01-10 19:41 UTC, deoxis9001 commented on worlds/dlcquest/__init__.py
> +        "A guide to setting up the Archipelago DLCQuest game on your computer.",
c'est fixer

2024-01-10 19:42 UTC, axe-y approved these changes

2024-01-11 23:08 UTC, black-sliver approved these changes
just forwarding the world maintainer approval

2024-01-11 23:10 UTC, black-sliver requested changes
since the original was properly formatted, i would suggest to properly format the new code as well

2024-01-11 23:10 UTC, black-sliver commented on worlds/dlcquest/__init__.py
> +    setup_fr=Tutorial(
```suggestion
    setup_fr = Tutorial(
```

2024-01-11 23:10 UTC, black-sliver commented on worlds/dlcquest/__init__.py
> +    tutorials=[setup_en,setup_fr]
```suggestion
    tutorials = [setup_en, setup_fr]
```

2024-01-12 19:26 UTC, black-sliver approved these changes
Thanks!

2024-01-12 19:26 UTC, merged