TUNIC: Update game page for blurb about playing vanilla first
ArchipelagoMW/Archipelago pull request #2712
Opened 2024-01-12 19:47 UTC by ScipioWright

## What is this fixing or adding?
Add a section to the game page discouraging the player from playing the rando before playing vanilla, as that is a terrible idea.
Also changing settings -> options

## How was this tested?
Reading

## If this makes graphical changes, please attach screenshots.
N/A

2024-01-12 19:48 UTC, hatkirby approved these changes

2024-01-12 19:50 UTC, ReverM requested changes
There is spoiler material earlier in the page. I would move it above. Before the point that tells what is randomized ideally

2024-01-12 20:23 UTC, silent-destroyer approved these changes

2024-01-12 20:50 UTC, ReverM approved these changes
LGTM

2024-01-12 22:00 UTC, black-sliver commented on worlds/tunic/docs/en_Tunic.md
> +**Play vanilla first.** It is **_heavily discouraged_** to play this randomizer before playing the vanilla game, moreso than most other games in Archipelago.
```suggestion
**Play vanilla first.** It is **_heavily discouraged_** to play this randomizer before playing the vanilla game.
```
I think this is bad. You probably haven't played them all and you can't possibly know which games will come next.

2024-01-13 14:12 UTC, black-sliver approved these changes
Thanks!

2024-01-13 14:12 UTC, merged