Zillion: apworld-compatible module data
ArchipelagoMW/Archipelago pull request #2860
Opened 2024-02-24 20:16 UTC by beauxq

## What is this fixing or adding?

changed some module data access to use `pkgutil`
so that it can be accessed from an apworld

I think that makes it work as an internal apworld.
("internal" = `zillion/requirements.txt` is installed in the frozen build, and `ZillionClient.py` is built)

## How was this tested?

- zipped up the `zillion` folder
- renamed it `.apworld`
- removed the original `zillion` folder
- generated 1-player Zillion game
- played through the game connected to `MultiServer`, toggling map tracker off and on and watching it for accuracy

I did not test the whole Windows frozen build.
(I don't know how to build it and don't use Windows.)
But I'm confident any problem with that would be found in release candidate phase.

2024-02-24 20:21 UTC, beauxq commented
`affects: core` is just the `setup.py` removing Zillion from the apworld exclusion list

2024-02-26 04:50 UTC, remyjette approved these changes
> I did not test the whole Windows frozen build.
> (I don't know how to build it and don't use Windows.)

I just tested freezing it, and instead of a `lib/worlds/zillion/` folder there is now a `lib/worlds/zillion.apworld` 🥳 

Launching Zillion both via the Launcher and via ArchipelagoZillionClient.exe work.

Map in the client looks right.

Ran a test gen with ArchipelagoGenerate.exe, it asked for my ROM then generated successfully.
Open Patch in the launcher on the apzd which launched the zillion client and got myself a patched .sms ROM.

2024-03-03 12:51 UTC, black-sliver requested changes
Client change look good (map shows up), but the world is still not fully APWorld-compatible and fails to load for py3.8 here:
https://github.com/beauxq/Archipelago/blob/zillion-apworld-module-data/worlds/zillion/__init__.py#L28

See https://github.com/ArchipelagoMW/Archipelago/blob/main/docs/apworld%20specification.md#caveats

2024-03-03 15:22 UTC, black-sliver approved these changes
Thanks!

2024-03-03 15:23 UTC, merged