DKC3: Add CHANGELOG.md
ArchipelagoMW/Archipelago pull request #2946
Opened 2024-03-13 04:43 UTC by PoryGone

## What is this fixing or adding?
Adds a changelog markdown file to the DKC3 World.

## How was this tested?
I read it, and tossed it into a markdown renderer.

2024-03-13 05:06 UTC, nicholassaylor approved these changes
Log is nicely formatted and free of errors
LGTM

2024-03-13 19:39 UTC, Exempt-Medic requested changes
Minor formatting suggestions to match the other changelogs

2024-03-13 19:39 UTC, Exempt-Medic commented on worlds/dkc3/CHANGELOG.md
> +### Features
```suggestion
### Features:
```

2024-03-13 19:39 UTC, Exempt-Medic commented on worlds/dkc3/CHANGELOG.md
> +### Bugfixes:
```suggestion
### Bug Fixes:
```

2024-03-13 19:39 UTC, Exempt-Medic commented on worlds/dkc3/CHANGELOG.md
> +### Features
```suggestion
### Features:
```

2024-03-14 02:24 UTC, Exempt-Medic approved these changes

2024-03-15 12:57 UTC, ThePhar approved these changes

2024-03-15 12:57 UTC, merged