SMW: Add CHANGELOG.md
ArchipelagoMW/Archipelago pull request #2947
Opened 2024-03-13 04:43 UTC by PoryGone

## What is this fixing or adding?
Adds a changelog markdown file to the SMW World.

## How was this tested?
I read it, and tossed it into a markdown renderer.

2024-03-13 05:15 UTC, nicholassaylor requested changes
Just two small changes, one typo, one style

2024-03-13 05:15 UTC, nicholassaylor commented on worlds/smw/CHANGELOG.md
> +		- Blocks that are unreachable without glitches/unreasonable movement
```suggestion
			- Blocks in Top Secret Area & Front Door/Bowser Castle
			- Blocks that are unreachable without glitches/unreasonable movement
```
For emphasis

2024-03-13 05:15 UTC, nicholassaylor commented on worlds/smw/CHANGELOG.md
> +	- Removal of `orld: MultiWorld` across the world
```suggestion
	- Removal of `world: MultiWorld` across the world
```

2024-03-13 05:26 UTC, nicholassaylor approved these changes
LGTM

2024-03-13 19:44 UTC, Exempt-Medic requested changes
Minor suggestion. Did not do a close reading.
Sidenote: I realized that whether or not you used `:` when starting a list or an inner section is inconsistent. It's fine to leave it, I just thought I'd point it out

2024-03-13 19:44 UTC, Exempt-Medic commented on worlds/smw/CHANGELOG.md
> +### Features
```suggestion
### Features:
```

2024-03-13 19:44 UTC, Exempt-Medic commented on worlds/smw/CHANGELOG.md
> +### Features
```suggestion
### Features:
```

2024-03-14 02:25 UTC, Exempt-Medic approved these changes

2024-03-15 12:56 UTC, ThePhar approved these changes

2024-03-15 12:56 UTC, merged