Celeste 64: Add CHANGELOG.md
ArchipelagoMW/Archipelago pull request #2948
Opened 2024-03-13 04:43 UTC by PoryGone

## What is this fixing or adding?
Adds a changelog markdown file to the Celeste 64 World.

## How was this tested?
I read it, and tossed it into a markdown renderer.

2024-03-13 05:16 UTC, nicholassaylor requested changes
One typo, otherwise good

2024-03-13 05:16 UTC, nicholassaylor commented on worlds/celeste64/CHANGELOG.md
> +- Goal is to collect a cetain amount of Strawberries and visit Badeline on her island
```suggestion
- Goal is to collect a certain amount of Strawberries and visit Badeline on her island
```

2024-03-13 05:28 UTC, nicholassaylor approved these changes
LGTM

2024-03-13 19:41 UTC, Exempt-Medic requested changes
Minor formatting suggestions, did not do a close reading

2024-03-13 19:41 UTC, Exempt-Medic commented on worlds/celeste64/CHANGELOG.md
> +### Features
```suggestion
### Features:
```

2024-03-13 19:41 UTC, Exempt-Medic commented on worlds/celeste64/CHANGELOG.md
> +- Items included
```suggestion
- Items included:
```

2024-03-14 02:26 UTC, Exempt-Medic approved these changes

2024-03-15 12:56 UTC, ThePhar approved these changes

2024-03-15 12:57 UTC, merged