SC2: Local Victory Items option
ArchipelagoMW/Archipelago pull request #3017
Opened 2024-03-23 18:56 UTC by Alchav

Wrote this for my own purposes but thought I would offer it upstream.

## What is this fixing or adding?
Adds a Local Victory Items option to SC2. This places local items into Victory locations, which prevents other players' !collects from marking missions as completed when they are not. Items are not locked, but an Item Rule is added to these locations to ensure that if Progression Balancing, etc, swap items out, they do so only with other local items. 

## How was this tested?
Generating a multiworld and ensuring all victory locations contained local items.

2024-03-24 17:25 UTC, Alchav commented
@Ziktofel

2024-03-24 21:21 UTC, Ziktofel commented
I want some playtesting there to ensure that nothing breaks

2024-03-24 21:30 UTC, Ziktofel commented on worlds/sc2/__init__.py
> +                         if location.name.endswith((": Victory", ": Defeat"))]
The endswith is used elsewhere, should be wrapped into a function (`is_victory_location`)

2024-03-26 17:45 UTC, Alchav commented on worlds/sc2/Options.py
> +    local_victory_items: LocalVictoryItems
Fixed

2024-03-27 17:49 UTC, Ziktofel commented
Did you do a playtest?

2024-03-28 20:26 UTC, Ziktofel commented
I want to be sure that it won't mess up beat events and things like that are also attached to victory locations

2024-04-14 17:17 UTC, Alchav commented
> I want to be sure that it won't mess up beat events and things like that are also attached to victory locations (a multiworld with 2 tiny grids using `terribleterribledamage` should suffice)
> 
> As we're heading to release I don't want to introduce any game-breaking bug in the release

Played a two-player game, one with local victory items on, one without. The one with the option on had local items in all victory locations, and there were no issues completing.

2024-04-14 22:07 UTC, Ziktofel approved these changes

2024-04-14 22:50 UTC, Bicoloursnake approved these changes
I'm more familiar with SC2 specific shenanigans than the general AP architecture, but this all looks correct to me. Thanks for the new cool option!

2024-04-15 01:32 UTC, MatthewMarinets commented
Is it possible to set up a unit test for this? I'm working on refactoring this code on my branch, it would be nice to have a way to verify I don't break this functionality when I merge it in.

2024-04-15 02:13 UTC, MatthewMarinets commented
Berserker just raised a good point in the discord -- do we want to solve this problem in this way? An alternative approach would be to use a datastore to save mission completion state separately from items. That way, mission unlocks would not be affected by `!collect` / `!release`. I agree that method would be cleaner.

2024-05-29 01:42 UTC, NewSoupVi commented
What are you wanting to go with?

For the record, I agree with the datastorage approach over this

2024-06-06 20:00 UTC, Ziktofel commented
`!release` should always lead to all missions done. It'd be weird if all missions are only white (cleared) or grey (inaccessible) and nothing is blue (able to play, some checks left) if there's at least one grey mission

BTW nothing's changed since my last code review approval.

2024-06-13 05:14 UTC, NewSoupVi commented
Ok, I finally had a look at this.

This current implementation breaks plando.

If a user plandos one of the randomly selected items that get placed during the restrictive_fill with `from_pool`, the generation will crash because the item has been taken out of the pool before plando runs.

"Place random local items on local checks" is a use case that will **always run into this issue** unless the relevant filling is done in `fill_hook`.
Question at this point: Was the item rule not enough on its own? Did that lead to fill errors?

2024-07-28 19:07 UTC, Ziktofel requested changes
There's already a function to get locations subject to plando

```python
def get_plando_locations(world: World) -> List[str]:
    """

    :param multiworld:
    :param player:
    :return: A list of locations affected by a plando in a world
    """
    if world is None:
        return []
    plando_locations = []
    for plando_setting in world.multiworld.plando_items[world.player]:
        plando_locations += plando_setting.get("locations", [])
        plando_setting_location = plando_setting.get("location", None)
        if plando_setting_location is not None:
            plando_locations.append(plando_setting_location)

    return plando_locations
```

Discard any plando'd locations from victory_locations

2024-08-07 20:50 UTC, closed without merging