CommonClient: update commands to function without local apworld
ArchipelagoMW/Archipelago pull request #3045
Opened 2024-03-28 03:58 UTC by qwint

## What is this fixing or adding?
Currently CommonClient commands like /Items do not function if the user connects to a slot for a world they do not have installed locally,
this PR aims to trust whatever datapackage matches our game from the server if it exists, and trust the AutoRegister like before if it doesn't (so game extensions on CommonClient can access the information before connecting as well)

Note: i'm not married to the way i got the current checksum for the connected game or the variable name 'lookup' for the output loops, so any prettier ideas welcome

Note2: unless item/location groups are sent over the wire somewhere, /item_groups and /location_groups will not function without an apworld. it doesn't seem to have much support to change that, but if it does those commands can be updated to work without a local apworld.

## How was this tested?
lightly, 
connecting to an apworld i did not have installed (outer wilds) and confirming i could see items and locations, and that item groups and location groups had a relevant error message
launching a couple game clients and using all the commands before connecting (and for one or two games i had, i connected and confirmed they didn't break)

## If this makes graphical changes, please attach screenshots.

2024-03-28 04:03 UTC, EmilyV99 approved these changes
LGTM (didn't test myself, but looks straightforward enough, and don't see any obvious errors)

2024-03-28 14:30 UTC, Berserker66 commented
I'd say this would  be better with https://github.com/ArchipelagoMW/Archipelago/pull/2561, so it can pull the group data too.

2024-04-12 22:23 UTC, qwint commented
overhauled how item_groups and location_groups are handled when connected, I did some testing with #2561 but it gave me a slightly different idea while i was still figuring out how to structure the changes.

Now they, if connected, check a cached lookup by checksum + game and return the data
if that information doesn't exist it sends the query and tells the user to retry the command (as the response + handling should have it ready by the time they re-send the command)

with the 2561 updates it should just be able to be checked and populated during prepare_data_package() but I'd rather change the functionality with that update vs wait on it

2024-12-24 02:09 UTC, qwint commented
core is already caching current datapackage checksums because of #3722 
so when conflicts are resolved this pr should use/enhance those instead of making their own cache (as it currently does)

2025-02-05 05:08 UTC, qwint commented
pulls in datapackage version removal from #4487 to simplify handling, marking waiting on other to represent that

2025-02-05 05:13 UTC, qwint commented
I also potentially want to explore doing all of the group checking in the rest of the consume datapackage code, and save them to the same datapackage cache, but didn't have a great idea of how to manage if a datapackage cache exists but is from before this update so it doesn't have groups cached vs has everything cached but just doesn't not have groups

2025-02-26 00:45 UTC, alwaysintreble requested changes
Overall the changes look good. Pointed out a few things that look like they may actually be incorrect, and could really use return typing on all the modified/new methods

2025-02-26 00:45 UTC, alwaysintreble commented on CommonClient.py
> +            return AutoWorldRegister.world_types[self.ctx.game]
hopefully we never actually hit this use case (and if so maybe it should at least log a warning?) but this return seems wrong since it's returning a World instead of a dict (speaking of maybe add some typing to the method signature).

2025-02-26 00:45 UTC, alwaysintreble commented on CommonClient.py
> +            self.output(key)
idk if it's actually used for anything but seems like you should be returning True after this. (we really need typing on these methods)

2025-02-26 00:45 UTC, alwaysintreble commented on CommonClient.py
> +                self.output(entry)
same here and just below

2025-02-26 00:55 UTC, qwint commented on CommonClient.py
> +            self.output(key)
like, `return bool(lookup)` i'm not sure when that would be helpful but we could add it? this is just a new helper function for these commands so if we don't need it here i'm not sure when we would need it

2025-02-26 00:57 UTC, qwint commented on CommonClient.py
> +            return AutoWorldRegister.world_types[self.ctx.game]
I think i wrote that before i pre-populated checksums if ctx.game was set at init, it can probably be safely removed/throw warnings

2025-04-05 20:50 UTC, alwaysintreble commented
https://github.com/qwint/Archipelago/pull/3

2025-04-07 21:40 UTC, alwaysintreble approved these changes

2025-05-02 23:39 UTC, qwint commented
with #4487 merged this is no longer waiting on anything else

2025-07-26 02:18 UTC, Berserker66 approved these changes

2025-07-26 02:18 UTC, merged