The Witness: Make joke hints local
ArchipelagoMW/Archipelago pull request #3049
Opened 2024-03-28 15:36 UTC by hatkirby

## What is this fixing or adding?
Joke hints are being moved into the client, so they no longer need to be stored here. This change also nulls out joke hints sent to the client, which is needed for it to know to generate a joke hint locally.

Client PR: NewSoupVi/The-Witness-Randomizer-for-Archipelago#28

## How was this tested?
Test generations with and without audio log hints. Game was closed and reopened to ensure consistency.

## If this makes graphical changes, please attach screenshots.

2024-03-28 15:54 UTC, NewSoupVi commented
Waiting on client PR: https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/pull/28

2024-03-28 16:35 UTC, NewSoupVi requested changes
Can't request changes to that line but

```
        credits_hint = (
            "This Randomizer is brought to you by\n"
            "NewSoupVi, Jarno, blastron,\n"
            "jbzdarkid, sigma144, IHNN, oddGarrett, Exempt-Medic, hatkirby.", -1, -1
        )
```

2024-03-29 00:50 UTC, hatkirby commented
That's correct.

2024-03-29 05:35 UTC, NewSoupVi approved these changes
https://github.com/NewSoupVi/The-Witness-Randomizer-for-Archipelago/pull/28 is merged. All of my concerns have been addressed.

2024-03-29 14:20 UTC, NewSoupVi approved these changes

2024-03-29 14:22 UTC, NewSoupVi commented on worlds/witness/__init__.py
> +            self.log_ids_to_hints[int(audio_log, 16)] = ("", -1, -1)
Like, have it use a for loop or even `self.log_ids_to_hints.update({int(audio_log, 16): ("", -1, -1) for audio_log in audio_logs})`

2024-03-29 14:42 UTC, NewSoupVi commented
Moving this to core review because it adds 3 lines

2024-03-29 14:49 UTC, Exempt-Medic approved these changes
My only comment got addressed in the past hour. The changes all LGTM and it still generates with and without joke hints.

2024-04-07 21:35 UTC, NewSoupVi commented
This PR will likely conflict with https://github.com/ArchipelagoMW/Archipelago/pull/3007, which I absolutely need to be merged before anything else.

2024-04-13 22:33 UTC, Berserker66 approved these changes

2024-04-13 22:46 UTC, merged