SC2: Fix so End Game gets proper priority for final mission
ArchipelagoMW/Archipelago pull request #3176
Opened 2024-04-19 01:17 UTC by t3hf1gm3nt

## What is this fixing or adding?
Start of discord conversation related to this: https://discord.com/channels/731205301247803413/980554570075873300/1230675826467668059
TL;DR: End Game seems to have been bumped up from a Hard mission to a Very Hard mission near the end of dev for the big SC2 update. However, this change wasn't reflected in a few areas. Because of this, currently End Game cannot be considered a final mission, or has a very low chance to be considered one. The test case that brought this up was a mixed WoL/NCO grid with All In excluded would not set End Game as the final mission. It would end up picking one of the other hard missions from either WoL or NCO instead. I am not sure what other ramifications this might cause, but at least for the test case that brought this about, the contents of this PR bring about the desired result

## How was this tested?
Several test gens with a yaml with the following options:
  mission_order: grid
  enable_wol_missions: 'true'
  (all other campaigns: false)
  enable_nco_missions: 'true'
  shuffle_campaigns: 'true'
  excluded_missions: [All-In]
## If this makes graphical changes, please attach screenshots.
N/A

2024-04-19 01:27 UTC, Magnemania requested changes
I believe End Game: Victory needs to be removed from campaign_alt_final_mission_locations, as well.

2024-04-19 12:05 UTC, Ziktofel commented
I'll decide after I'll get feedback on Discord post: https://discord.com/channels/731205301247803413/980554570075873300/1230850327880929300

2024-04-19 20:40 UTC, Ziktofel commented
#3180 handles that in more complex way

2024-04-20 14:40 UTC, t3hf1gm3nt commented
#3180 does this and goes a step beyond, so closing this as it's redundant

2024-04-20 14:40 UTC, closed without merging