Core: increment version
ArchipelagoMW/Archipelago pull request #3312
Opened 2024-05-17 10:35 UTC by Berserker66

## What is this fixing or adding?
increment version

2024-05-18 13:12 UTC, black-sliver approved these changes
Not sure when we want to merge it, but change is fine

2024-06-03 19:38 UTC, nicholassaylor requested changes
Reminder to change the version number because of #1933

2024-06-03 19:38 UTC, nicholassaylor commented on Utils.py
> +__version__ = "0.4.7"
```suggestion
__version__ = "0.5.0"
```

2024-06-03 20:02 UTC, ThePhar commented
> Reminder to change the version number because of #1933

Version is already 0.5.0 as of #1933, so I'll just close this PR.

2024-06-03 20:02 UTC, closed without merging

2024-06-03 20:22 UTC, Berserker66 commented
Darn, you took my technically by the rules shotgun away.