Core: move `OptionGroup` definition to `Options.py`
ArchipelagoMW/Archipelago pull request #3325
Opened 2024-05-18 13:07 UTC by beauxq

## What is this fixing or adding?

`BaseClasses.py` doesn't seem like the right place for this.
- `BaseClasses.py` was otherwise untouched by the PR that introduced this feature
- World devs have already noticed that it's nicer to define their `OptionGroup`s in their world's options module, which often doesn't import anything else from `BaseClasses.py`
  - Adding `BaseClasses` to those imports increases the risk of having to deal with circular import issues.

## How was this tested?

opened an option page from WebHost, observed the option groups, generated a game from the option page

2024-05-18 19:55 UTC, alwaysintreble requested changes

2024-05-18 19:55 UTC, alwaysintreble commented on Options.py
> +    """Options to be in the defined group. """
```suggestion
    """Options to be in the defined group."""
```

2024-05-18 19:55 UTC, alwaysintreble commented on Options.py
> +    """Name of the group to categorize this option in for display on the WebHost and in generated YAMLS."""
```suggestion
    """Name of the group to categorize these options in for display on the WebHost and in generated YAMLS."""
```

2024-05-18 19:55 UTC, alwaysintreble commented on Options.py
> +    """Define a grouping of options"""
```suggestion
    """Define a grouping of options."""
```

2024-05-18 22:07 UTC, Exempt-Medic approved these changes
Change makes sense and fixes what I thought was an unusual decision. Tested it locally, it worked.

2024-05-19 00:39 UTC, alwaysintreble approved these changes

2024-05-19 02:39 UTC, Berserker66 approved these changes

2024-05-19 02:40 UTC, merged