Muse Dash: Option Groups and Options Rework
ArchipelagoMW/Archipelago pull request #3434
Opened 2024-06-02 04:56 UTC by DeamonHunter

## What is this fixing or adding?
Does the following:
- Adds options group
- Include Songs and Starter Songs must have their respective song dlc's enabled.
- Traps now are selected individually rather than by group

There sadly was one option that I couldn't change, and that was the `Allow [Muse Plus] DLC Songs`. I would like this to be in DLC Packs, but as the Presets set this value, it currently cannot be in them.

## How was this tested?
With the newly added tests, as well as test generations to confirm things are working as intended.

## If this makes graphical changes, please attach screenshots.
![firefox_dG32BPai2S](https://github.com/ArchipelagoMW/Archipelago/assets/7556376/d2429dea-386b-44c1-95fc-6ab31c11896d)
![firefox_1Pes18y6Um](https://github.com/ArchipelagoMW/Archipelago/assets/7556376/9d387985-579a-48b5-91fd-c629bd953c5c)

2024-06-02 18:48 UTC, Exempt-Medic requested changes
A few minor comments/questions/corrections

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/Options.py
> +    valid_keys = [trap for trap in MuseDashCollections.trap_items.keys()]
Unsure if this is intended, but the way these display on WebHost matches the order they are declared in `trap_items`, in other words, they aren't alphabetical.

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/Options.py
Just checking that the way the tooltips display on the new WebHost are how you want them to display. Most games have changes their docstrings to display in a different format

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/Options.py
> +    """Choose which DLC Packs that will be included in the pool of chooseable songs."""
```suggestion
    """Choose which DLC Packs will be included in the pool of chooseable songs."""
```

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/Options.py
> +    - If there being too many included songs, this will act as a whitelist ignoring song difficulty.
```suggestion
    - If there are too many included songs, this will act as a whitelist ignoring song difficulty.
```

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/test/TestCollection.py
> +            self.assertNotIn(song_name, songs, f"Song '{song_name}' wasn't removed correctly.")
End of file newline
```suggestion
            self.assertNotIn(song_name, songs, f"Song '{song_name}' wasn't removed correctly.")
            
```

2024-06-02 18:48 UTC, Exempt-Medic commented on worlds/musedash/test/TestPlandoSettings.py
> +        self.assertNotIn("Fireflies", songs, "Logical songs has added a filtered a plando song: Fireflies")
EoF newline
```suggestion
        self.assertNotIn("Fireflies", songs, "Logical songs has added a filtered a plando song: Fireflies")
        
```

2024-06-03 09:31 UTC, DeamonHunter commented on worlds/musedash/Options.py
Thanks for reminding me. Its now set up so there isn't as much white space at the front of them.

2024-06-03 09:33 UTC, DeamonHunter commented
After the fix on main, the old Just As Planned (Muse Plus) DLC has now been merged with the rest. As well as a bunch of smaller fixes.

2024-06-03 10:25 UTC, DeamonHunter commented
I fixed the failing default options test. Current test failure is one on main.

Default Yaml Generation fails to put a # in front of a comment if it doesn't have more than 4 spaces. And I think the `-` in the docs on sets meant that it added invalid options to the sets.

2024-06-03 10:48 UTC, Exempt-Medic commented
The way to fix the spacing is this:
```
"""
Docstring start on the second line
"""
```

2024-06-03 13:17 UTC, Exempt-Medic approved these changes
Changes LGTM. The WebHost display all looks great, new option groups work, old options correctly throw errors from being Removed, docstrings look good grammar wise, trap adjustments work properly, new tests make sense (and pass). Just one tiny correction

2024-06-04 19:44 UTC, NewSoupVi approved these changes

2024-06-04 19:45 UTC, merged