Cleanup: MMBN3 Typo for SloGauge
ArchipelagoMW/Archipelago pull request #3457
Opened 2024-06-03 21:39 UTC by Hexadigital

## What is this fixing or adding?
This fixes the Archipelago item name for SloGauge in Mega Man Battle Network 3 which was misspelled as SloGuage, causing the typo to appear in the Archipelago client and in games that display AP item names.

## How was this tested?
Not necessary due to the change only being swapping two characters in a single string.

## If this makes graphical changes, please attach screenshots.
N/A

2024-06-04 03:06 UTC, nicholassaylor requested changes
You missed a reference in `Items.py`
https://github.com/ArchipelagoMW/Archipelago/blob/06e65c1dc6ce4a1564d1b6924b83a0c9546011ec/worlds/mmbn3/Items.py#L174

2024-06-04 06:54 UTC, Hexadigital commented
Sorry, I'm not sure what you're referencing there - would you like the variable name updated as well? I did not alter that in the file I edited.

2024-06-04 17:06 UTC, nicholassaylor commented
> Sorry, I'm not sure what you're referencing there - would you like the variable name updated as well? I did not alter that in the file I edited.

I apologize for not being clear before. But yes, since the string is being corrected, the variable name in both `/Names/ItemName.py` and `Items.py` should probably be changed as well since they are both mispelled and the variables try to match the string closely. It's more a consistency thing rather than strictly correct or incorrect. Changing the names or not should not affect generation at all.

2024-06-05 03:50 UTC, Hexadigital commented
Okay! Those have been adjusted as well.

2024-06-05 05:05 UTC, nicholassaylor approved these changes
Changes LGTM just waiting fit @digiholic to confirm the charges

2024-06-20 02:48 UTC, Exempt-Medic approved these changes
LGTM and covers every instance of `SloGuage`, just needs maintainer approval

2024-10-23 16:49 UTC, digiholic commented
Ah, woops. I get so many messages about merges that I never saw this notification amongst them all. I need to clean up my email notifications...

2024-10-23 16:49 UTC, digiholic approved these changes

2024-11-11 22:59 UTC, Berserker66 approved these changes

2024-11-11 23:03 UTC, merged