Gauntlet Legends: Implement New Game
ArchipelagoMW/Archipelago pull request #3499
Opened 2024-06-09 05:51 UTC by jamesbrq

## What is this fixing or adding?
Adds Gauntlet Legends on the N64 as a supported game.

## How was this tested?
Through months of testing in both syncs and asyncs

## If this makes graphical changes, please attach screenshots.
N/A

2025-01-15 04:06 UTC, qwint commented on worlds/gl/__init__.py
> +        "GauntletLegendsClient",
You should not define Component.script_name nor define a client in root, worlds that do are getting phased away from that and any new game PR should not be merged while using them

2025-01-15 05:30 UTC, jamesbrq commented on worlds/gl/__init__.py
> +        "GauntletLegendsClient",
Ive removed the root client, only the apworld client remains. Is there anything I need to change when adding my component to align with the new norm?

2025-01-15 06:57 UTC, qwint commented on worlds/gl/__init__.py
> +        "GauntletLegendsClient",
what you've changed is good, thanks
will try to make some time to review the rest of the world later

2025-01-15 19:04 UTC, qwint requested changes
skimmed rom-based code and docs and commented on anything that stood out, but not a full review on those parts
otherwise pure code review, I did run webhost and glance at the pages there, but otherwise ran no tests/gens/games

2025-01-17 06:20 UTC, jamesbrq commented on worlds/gl/__init__.py
> +    rom_start: bool = False
This I will look into in the future as at the moment Im not sure how Retroarch handles launching with a ROM, hence why I defaulted it to false.

2025-01-17 06:22 UTC, jamesbrq commented on worlds/gl/__init__.py
> +        self.options.max_difficulty_value.value = max(self.options.max_difficulty_value.value, self.options.local_players.value)
This is documented under MaxDifficultyRange in Options.py

2025-01-17 06:31 UTC, jamesbrq commented on worlds/gl/__init__.py
> +        ]
If an item is still another gauntlet legends player, it still needs to be converted into a purple coin ingame. This is just an exception to the normal item replacement in Rom.py since the compression of the file has contains the items is wonky and I cant get it to recompress correctly. This is just a workaround for that.

2025-01-17 06:52 UTC, jamesbrq commented on worlds/gl/Options.py
> +class DeathLink(Toggle):
Do I need to do anything to add death_link to my yaml then if I inherit it? Can I remove my own entirely?

2025-01-17 07:00 UTC, jamesbrq commented on worlds/gl/Regions.py
> +    connection.connect(target_region)
Is there an example of Region.connect() being used anywhere?

2025-01-17 08:54 UTC, qwint approved these changes
besides the World.disabled_locations classvar issue everything else at this point is nitpicks and looks good either way
again, pure code review, no tests/gens/games ran

2025-01-17 08:54 UTC, qwint commented on worlds/gl/__init__.py
> +    disabled_locations: typing.Set[LocationData] = set()
same point as your `death` classvar, if mutated without being set it's shared across classes so I'd recommend against setting the value in the class and to set it in generate_early instead

2025-01-17 08:54 UTC, qwint commented on worlds/gl/Rules.py
> +                            state.prog_items[world.player]["stones"] >= difficulty_lambda[level_id_][difficulty],
you can still use the state.has() helpers on custom-added items like your `stones` here, not required because it's very technically slower to use the helper, but will cut down on refactors if the underlying counters change in the future
```suggestion
                            state.has("stones", self.player, difficulty_lambda[level_id_][difficulty])
```

2025-01-17 08:54 UTC, qwint commented on worlds/gl/Regions.py
> +    connect(world, names, "Menu", "Desecrated Temple",
you might get in formatting trouble since you did
```py
function(x,
    y,
    z,
)
```
instead of 
```py
function(x,
         y,
         z,
)
```
but its not a hill i'm willing to die on personally

2025-01-17 08:54 UTC, qwint commented on worlds/gl/__init__.py
> +            if item.item_name == "Anti-Death Halo" and (self.options.traps_choice.value == self.options.traps_choice.option_only_death or self.options.traps_choice.value == self.options.traps_choice.
another instance of checking option value vs the instance's classvar instead of using a string or importing the class

2025-01-17 08:54 UTC, qwint commented on worlds/gl/Options.py
> +class DeathLink(Toggle):
correct, you would not need to define DeathLink at all if you import and add the DeathLinkMixin to your Options DataClass

2025-01-17 08:54 UTC, qwint commented on worlds/gl/Regions.py
> +    connection.connect(target_region)
there's a handful in main but it's a bit hard to sort them vs Entrance.connect uses
https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/zork_grand_inquisitor/world.py#L138

2025-01-17 08:54 UTC, qwint commented on worlds/gl/__init__.py
> +        for item in [item_ for item_ in item_list if ItemClassification.progression in item_.progression or ItemClassification.useful in item_.progression and item_ not in precollected and item_ not
FYI in this general section you go over the style guide's 120 character limit a few times, and while it is a guide and not a requirement breaking comprehensions up like this is pretty simple and can make them easier to read too
```suggestion
        for item in [item_ for item_ in item_list
                     if ItemClassification.progression in item_.progression
                     or ItemClassification.useful in item_.progression
                     and item_ not in precollected
                     and item_ not in skipped_items
                     ]:
```

2025-01-17 08:54 UTC, qwint commented on worlds/gl/__init__.py
> +                                                        or ("Mirror" in item.item_name and self.options.mirror_shards == 0)]
my previous comment on this section intended to bring all the if option=something to be checked only once instead of each of these be checked per (relevant) item,
I would still recommend doing that and building out a set of item substrings that need to be skipped to be checked later

2025-01-17 20:33 UTC, qwint commented on worlds/gl/__init__.py
> +            if item.item_name == "Anti-Death Halo" and "Death" not in skipped_items and self.options.traps_frequency is not "normal":
```suggestion
            if item.item_name == "Anti-Death Halo" and "Death" not in skipped_items and self.options.traps_frequency != "normal":
```

2025-01-17 20:35 UTC, qwint commented on worlds/gl/__init__.py
> +            if item.item_name == "Anti-Death Halo" and "Death" not in skipped_items and self.options.traps_frequency is not "normal":
whoops you already caught that

2025-01-17 20:36 UTC, qwint approved these changes
context of my review has not changed, but all my issues and requests are handled

2025-02-22 00:05 UTC, massimilianodelliubaldini commented
@jamesbrq Just for your awareness. Unless something important to your world was added to AP core recently, or you need to resolve conflicts, you don't need to keep merging `main` into your `gl` branch. It sends a notification to everyone who is following the PR, which may not be necessary. Otherwise, don't worry about GitHub saying "Your branch is out-of-date," it's ok if it sits like until other peer reviewers come along.

2025-06-08 21:47 UTC, qwint commented on worlds/gl/Rom.py
> +GL_HASH = "9cb963e8b71f18568f78ec1af120362e"
FYI https://github.com/ArchipelagoMW/Archipelago/blob/main/settings.py#L373
FilePath and it's subclasses already have a way to validate a md5 hash against the user-chosen file

2025-06-08 21:53 UTC, jamesbrq commented on worlds/gl/Rom.py
> +GL_HASH = "9cb963e8b71f18568f78ec1af120362e"
Forgot about this, was looking at some older SNES implementations

2025-06-12 20:39 UTC, qwint commented on worlds/gl/Rom.py
>          with open(get_settings().gl_options.rom_file, "rb") as infile:
should use the World classattr when possible
```suggestion
        from . import GauntletLegendsWorld
        GauntletLegendsWorld.settings.rom_file.validate()
        with open(GauntletLegendsWorld.settings.rom_file, "rb") as infile:
```

2025-11-03 14:24 UTC, ScipioWright approved these changes
Only did code review.
Did not do test gens.
Did not test the client.
Code looks good to me, minor comments on formatting.

2025-11-03 14:24 UTC, ScipioWright commented on worlds/gl/Locations.py
> +valley_of_fire: typing.List[LocationData] = [
```suggestion
valley_of_fire: list[LocationData] = [
```
I know this is a result of the PR being open for so long, but you should still probably just update this and similar instances to use the newer typing

2025-11-03 14:24 UTC, ScipioWright commented on worlds/gl/__init__.py
> +        patch = GLProcedurePatch(player=self.player, player_name=self.multiworld.player_name[self.player])
```suggestion
        patch = GLProcedurePatch(player=self.player, player_name=self.player_name)
```
Also quick reminder to make sure that possible player names won't cause issues with making your patch, since player names can be most unicode stuff

2025-11-03 14:24 UTC, ScipioWright commented on worlds/gl/Options.py
> +class Obelisks(Choice):
Obelisks and MirrorShards should probably be DefaultOnToggles instead of choices, but I understand if you want to just leave it as is

2025-11-03 15:08 UTC, beauxq commented on worlds/gl/Arrays.py
> +    (0x0, 0x1, 0x0): "Health",
These keys are duplicated, so `"Fruit"` and `"Meat"` values will not exist in this data.

2025-11-03 16:13 UTC, Rooby-Roo requested changes
Looked through the world code only, as I am not qualified to talk on client or ROM things. Only really have one comment.

I can attest to the stability of this world as someone who has watched it develop over the course of many asyncs.

2025-11-03 16:13 UTC, Rooby-Roo commented on worlds/gl/__init__.py
> +    Gauntlet Legends
This string is shown on the website. You'll want it to be a human-readable and parse-able sentence.

2025-11-03 19:02 UTC, palex00 approved these changes
I tested the following:
- I tested the game's determinism. It is deterministic.
- I fuzzed the game 10.000 times with one YAML. Only 3 gens failed. Dev is informed.
- I fuzzed the game 1000 times with three YAMLs. Zero failed.
- The game generates with other games.

2025-11-03 20:14 UTC, jamesbrq commented
Ran 10000 solo yamls with 0 failures, 1000 3 yaml games with 0 failures, and tested running on frozen with other games, all working fine on the latest commit

2025-11-03 21:15 UTC, beauxq commented on worlds/gl/Arrays.py
> +]
There is a common type of bug we've seen in apworlds with mutating static data.

You can see some people discussing this common type of bug here:
https://discord.com/channels/731205301247803413/1214608557077700720/1434721899094474812

I don't see this type of bug here currently. (I didn't look very hard.)
But even if the bug doesn't exist now, there's danger of introducing the bug in the future.

A good way to protect yourself against this bug is to make all static data immutable.

- instead of list - `my_data: list[int] = [2, 4, 6]`
  - use tuple - `my_data: Final[Sequence[int]] = (2, 4, 6)`
- instead of dict - `base_count: dict[str, int] = {...}`
  - use MappingProxyType - `base_count: Final[Mapping[str, int]] = MappingProxyType({...})`

This will help you make sure you don't accidentally modify data that shouldn't change.

I would recommend this for all the data in this file, and some in some other files.

these example use this imports:
```py
from collections.abc import Mapping, Sequence
from types import MappingProxyType
from typing import Final
```

2025-11-03 21:23 UTC, beauxq commented on worlds/gl/Arrays.py
> +mirror_levels = [bytes([0x6, 0x2]), bytes([0x5, 0x9]), bytes([0x5, 0x1]), bytes([0x5, 0x7])]
```py
bytes([0x6, 0x2])
```
This can be written like this:
```py
b"\x06\x02"
```
It's up to you whether you think that's more clear or less clear.
```py
>>> bytes([0x6, 0x2]) == b"\x06\x02"
True
```

2025-11-03 21:29 UTC, beauxq commented on worlds/gl/GauntletLegendsClient.py
> +        logger.info(f"InstantMax {('Enabled.' if self.ctx.glslotdata["instant_max"] else 'Disabled.')}")
using `"` inside an f-string like this works in Python 3.12, but it's a syntax error before 3.12.

2025-11-03 22:30 UTC, qwint commented on worlds/gl/GauntletLegendsClient.py
> +        logger.info(f"InstantMax {('Enabled.' if self.ctx.glslotdata["instant_max"] else 'Disabled.')}")
fixing this will also clear the flake8 error currently on the PR

2025-11-04 16:00 UTC, jamesbrq commented on worlds/gl/Arrays.py
> +mirror_levels = [bytes([0x6, 0x2]), bytes([0x5, 0x9]), bytes([0x5, 0x1]), bytes([0x5, 0x7])]
I personally prefer defining them as `bytes()` as long as thats fine then I'd prefer to keep it as such

2025-11-05 15:03 UTC, beauxq commented on worlds/gl/Rom.py
> +def get_level_data(stream: io.BytesIO, size: int, level=0) -> (io.BytesIO, LevelData):
```suggestion
def get_level_data(stream: io.BytesIO, size: int, level: int = 0) -> tuple[io.BytesIO, LevelData]:
```

2025-11-05 15:19 UTC, beauxq commented on worlds/gl/__init__.py
> +        precollected = [item for item in item_list if item in self.multiworld.precollected_items[self.player]]
Have you tested this `precollected` code?
It looks to me like `precollected` will always be empty, because `item` is an `ItemData`, and `self.multiworld.precollected_items` has `Item`, not `ItemData`

2025-11-05 15:31 UTC, jamesbrq commented on worlds/gl/__init__.py
> +        precollected = [item for item in item_list if item in self.multiworld.precollected_items[self.player]]
Your right I believe, first thing that comes to mind is just comparing the item names with `[item for item in item_list if item.item_name in [item.name for item in self.multiworld.precollected_items[self.player]]]`

2025-11-06 15:56 UTC, Rooby-Roo approved these changes
My requested change was corrected, so I'm marking this as an approval (not that this needs more peer reviewing at this point)

2025-11-25 19:58 UTC, 1-800-thewolf approved these changes
This worked great! There's a graphical bug I believe with the emulator/core which makes it hard to see the turbo charge in game, but otherwise no issues.

Played a 4 hour sync and it all worked as expected

2025-12-27 03:01 UTC, benny-dreamly reviewed
small review

2025-12-27 03:01 UTC, benny-dreamly commented on worlds/gl/Items.py
> +from worlds.gl import mirror_shards
please use relative imports for this, if you're importing from `__init__ .py` then you just write `from . import x`

2025-12-27 03:05 UTC, jamesbrq commented
For those I have re-requested a review from, I merged a PR into this branch that adds significant changes to the client and the ROM patching process, as well as other various changes including a few new options and conversion of my locations and items to JSON. As a courtesy I requested re-reviews from all of you. Anyone wanting to re-review the stability of the apworld in a sync or async game should do so on the v2.0.2 apworld. Thanks everyone as well for your reviews, I appreciate taking the time to review my PR.

2025-12-27 23:11 UTC, benny-dreamly approved these changes
Only did a code review, but looks fine. I unfortunately can't test the client part.

2025-12-29 16:26 UTC, Rooby-Roo reviewed
My previous review was based entirely on end-user experience and generation stability. I had not reviewed any code. Since I have had no new experience with the revamp that has happened, I feel unequipped to comment on it and as such will not be reviewing at this time.

2026-05-31 00:13 UTC, ScootyPuffJr1 commented
We had 7 worlds from this game in the last Big Async and didn't experience any issues whatsoever.

2026-07-11 13:38 UTC, NewSoupVi requested changes
Overall extremely solid, I had some nitpicks, the main thing I would like to see addressed is the goal condition

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Items.py
> +    return json.loads(pkgutil.get_data(__name__, "json/items.json").decode("utf-8"), object_hook=lambda d: ItemData(**d))
We don't love json definitions like you have because of the cost of File IO at world load time, but since you only have exactly one items file and one locations file (which would otherwise probably be one python file each anyway), I can accept it, especially since this PR has been open for so long. However, this should at least use orjson instead of json

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/__init__.py
> +    launch_subprocess(launch, name="GauntletLegendsClient", args=args)
You should generally use the `launch` function instead of the `launch_subprocess` function, because if your Client is opened via any of the direct launch methods, which I believe includes "double clicking the patch file", `launch_subprocess` will still always create a second process as if it was trying to not get in the way of Launcher UI, while `launch` will figure out that there is no Launcher UI & it doesn't need a second process for the client.

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/__init__.py
> +            "player": self.player,
Okay, I don't mean to be overly nitpicky here, but... :D That is info you should have available to you in any context where you have slot data. Your client knows which slot it's connected to

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/__init__.py
> +                item_required_count -= traps_frequency
The fact that this has no safeguard against `item_required_count` going negative slightly scares me. I assume the maximum of the TrapFrequency option (75) was set so that it's never higher than the amount of progression and useful items?

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Regions.py
> +    return lambda state, portals=bool(world.options.portals.value): (state.has(item, world.player) if portals else True)
This would be better as:

```py
def _portal_helper(item: str, world: "GauntletLegendsWorld") -> Callable:
    if world.options.portals.value:
        return lambda state, state.has(item, world.player)
    return lambda _: True
```

This way, `if world.options.portals.value` is evaluated once ahead of time, instead of every time the access rule is called.

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Regions.py
> +    return lambda state, portals=bool(world.options.portals.value): (state.has(item, world.player) if portals else True)
In fact, even more efficient would be:

```py
def _portal_helper(item: str, world: "GauntletLegendsWorld") -> Callable | None:
    if world.options.portals.value:
        return lambda state, state.has(item, world.player)
    return None
```

Since your `connect` helper already allows passing in `None` to not set a rule, which is superior because an assigned `lambda _: True` is slower than just calling the default function

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Rules.py
> +                            state.has("progression", world.player, max(difficulty_lambda[level_id_][difficulty] - (len(world.excluded_regions) * 4), 0))
As said in my other comment, moving static calculations outside of the lambda is more efficient for generation speed, and in this case it would make the code more readable too (in my opinion), something like this:

```py
if location.name not in world.disabled_locations:
    level_id_ = level_id >> 4
    difficulty = location.difficulty - 1
    expected_count = difficulty_lambda[level_id_][difficulty] - (len(world.excluded_regions) * 4)
    expected_count = max(expected_count, 0)
    add_rule(
        world.get_location(location.name),
        lambda state, expected_count_ = expected_count: state.has("progression", world.player, expected_count)
    )
```

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Rules.py
> +                            state.has("progression", world.player, max(difficulty_lambda[level_id_][difficulty] - (len(world.excluded_regions) * 4), 0))
In general, if you have anything *inside* of a lambda that performs arithmatic or `if` checks on "static" variables that do not themselves depend on the `state`, that work should be done ahead of time outside of the lambda.

2026-07-11 13:38 UTC, NewSoupVi commented on worlds/gl/Rules.py
> +                                >= world.options.boss_goal_count.value)
Once again same thing here, this function should probably return a Callable and be structured so that the if conditions are outside of the lambda, and **especially** so that the list comprehension is calculated ahead of time. If nothing else, that list comprehension being calculated inside the lambda is the biggest thing in this whole review I would like to see changed.

(Note: CollectionRule is an alias for Callable[[CollectionState], bool] that you can import)

```py
def goal_conditions(world: "GauntletLegendsWorld") -> CollectionRule:
    if world.options.goal == Goal.option_defeat_skorne:
        return state.can_reach("Gates of the Underworld", "Region", world.player)
    
    eligible_boss_regions = [
        boss for boss in boss_regions 
        if boss not in [
            level for region, levels in excluded_levels.items() 
            if region in world.excluded_regions for level in levels
        ]
    ]
    needed_boss_count = world.options.boss_goal_count.value

    return lambda state: sum(state.can_reach_region(boss, world.player) for boss in eligible_boss_regions) >= needed_boss_count
```

The code setting the rule would then obviously have to be modified in `__init__.py`:

```py
self.multiworld.completion_condition[self.player] = goal_conditions(self)

2026-07-11 13:41 UTC, NewSoupVi commented on worlds/gl/Rules.py
> +                                >= world.options.boss_goal_count.value)
The comprehension itself could also be made more efficient, but the point is that if it's done ahead of time, I don't mind it being inefficient - Because then it only happens once, not many many times across the placement generation.

2026-07-11 13:44 UTC, NewSoupVi commented on worlds/gl/Rules.py
> +                                >= world.options.boss_goal_count.value)
Oh, there is also something fun you could consider here: Remember how for the total count of acquired progression, you did it with a `collect` override that adds a "fake" item to state called "progression"? Well, in the time since you opened this PR, we have actually added a `world.reached_region` that you can override the exact same way, something like:

```py
    def reached_region(self, state: CollectionState, region: Region) -> None:
        super().reached_region(state, region)

        if region.name in self.eligible_boss_regions:
            state.prog_items[self.player]["bosses_defeated"] += 1
```

That's only a bonus thought though, you don't have to do that. The stuff I described above is more than enough.

2026-07-11 16:24 UTC, jamesbrq commented on worlds/gl/__init__.py
> +                item_required_count -= traps_frequency
With some additional safeguarding I was able to up it back to 90 without any repercussion, but yes it was due to too many traps being created, which was ultimately due to the lack of guards.

2026-07-11 16:26 UTC, jamesbrq commented on worlds/gl/Rules.py
> +                                >= world.options.boss_goal_count.value)
I decided not to override `world.reached_region()` as I think it is more clear what is happening in goal_conditions if the lambda continues to call `state.can_reach_region()`

2026-07-11 16:29 UTC, NewSoupVi approved these changes

2026-07-11 16:30 UTC, NewSoupVi commented
Approved in terms of code, I will run some randomized test generations and also rerun the unit tests (they're failing because of an unrelated issue that I *just* merged the MR for)

2026-07-11 17:26 UTC, merged