Change setup_en.md to use Latest releases page
ArchipelagoMW/Archipelago pull request #3543
Opened 2024-06-15 20:23 UTC by eudaimonistic

Really simple change to point users to the Latest release page instead of the Releases page.  Saw a user accidentally download 0.3.6 because it was the last item on the page (they're accustomed to scrolling down to the bottom of the page in GitHub for the Assets section), and this change prevents that outright.

Was tested by opening a single link in my preferred web browser.

2024-06-16 01:00 UTC, NewSoupVi requested changes
The wording and the link are slightly incompatible now, idk if a text change was considered and rejected, I think it'd be quite pertinent tho

2024-06-17 06:40 UTC, eudaimonistic commented
> The wording and the link are slightly incompatible now, idk if a text change was considered and rejected, I think it'd be quite pertinent tho

I didn't find the phrasing all too confusing, but I've made the adjustment to keep it internally consistent.

2024-06-19 02:05 UTC, Jouramie commented
That's a lot of scrolling to get to 0.3.6... 

Anyway, that seems like a helpful change. LGTM

2024-06-19 02:05 UTC, Jouramie approved these changes

2024-06-19 14:12 UTC, NewSoupVi approved these changes

2024-06-19 14:12 UTC, merged