Checksfinder Update/Cleaning
ArchipelagoMW/Archipelago pull request #3725
Opened 2024-08-01 19:01 UTC by Exempt-Medic

## What is this fixing or adding?

* Updates the ChecksFinder docs
* Removes ChecksFinder from the `non_apworlds` set
* Deletes `options.py` in favor of just `options_dataclass = PerGameCommonOptions`
* Simplifies creation of items and locations
* Simplifies rules setting
* Removed `topology_present` because the game is simple
* Rearranges `__init__.py` to be in call order
* Fixes import errors, `per_slot_randoms`, and user new helper functions

## How was this tested?

Generations, reading and comparing spoiler logs on the same seeds, playing games in multiworlds to completion, and viewing the website tracker.

2024-08-02 05:46 UTC, qwint approved these changes
changes are all reasonable, fixed all the things I had brought up in discord

mostly just did a code review
Did not test the non_apworlds change, lightly tested on 3.8/3.11, lightly generated, and tested the full refactors individually

Did get a strange error on testing py3.8 but I also was getting it on current main so unlikely it's an issue with this PR, the error for posterity: `FAILED test/programs/test_multi_server.py::TestResolvePlayerName::test_resolve - RuntimeError: There is no current event loop in thread 'MainThread'.`

2024-08-02 11:10 UTC, SunCatMC approved these changes
I approve these changes

2024-08-02 19:44 UTC, agilbert1412 requested changes

2024-08-02 19:44 UTC, agilbert1412 commented on worlds/checksfinder/__init__.py
> +            "eed_name": self.multiworld.seed_name,
`eed_name`?

2024-08-02 19:58 UTC, Exempt-Medic commented on worlds/checksfinder/__init__.py
> +            "eed_name": self.multiworld.seed_name,
Fixed

2024-08-02 20:07 UTC, agilbert1412 approved these changes

2024-08-05 22:10 UTC, NewSoupVi approved these changes
Waiting on an answer from alwaysintreble about whether `options_dataclass = PerGameCommonOptions` has bad implications somehow. It seems fine to me but he would know better than I

Otherwise this is good

2024-08-06 14:39 UTC, merged