[Core] Add World.visibility and improved mechanisms for world hiding/disabling
ArchipelagoMW/Archipelago pull request #3775
Opened 2024-08-11 19:36 UTC by BadMagic100

## What is this fixing or adding?
Adds improvements to hiding/disabling worlds via a Visibility enum for worlds, rather than just using world.hidden

The goals of this PR are as follows:
* [x] Add a way to disable a world without using worlds_disabled. This allows any work on these worlds to be done more seamlessly without risking conflicts when worlds are enabled/disabled
* [ ] Add a way to disable tests for and "soft disable" a world, causing it to be hidden and warn users when the world is used in generation. This would allow the world to be disabled in some way while still keeping it available for website users as long as it is not strictly broken
* [x] Document the process for soft disabling vs hard disabling a world
* [x] Use the new disabling mechanism for our 1 disabled world

If there is anything we should be doing in setup.py around worlds_disabled (there is a reference to it there) I'm not sure what.

## How was this tested?
WIP. So far, have tested that ori does not load/run tests and that hidden worlds are still hidden to the website

2024-08-11 21:02 UTC, agilbert1412 reviewed
I like what I'm seeing so far, but since the PR isn't complete, I'm not approving yet. Will look again later, don't hesitate to ping me if/when it's updated

2024-09-12 03:15 UTC, BadMagic100 commented
Logging some early feedback from black sliver in discord 

1. He doesn't like the name of the enum/field (minor)
2. Apparently pytest discovery will not play nice with these changes as written at this point in time

2024-09-15 20:45 UTC, BadMagic100 commented
@agilbert1412 this is ready for review

2024-09-25 01:01 UTC, agilbert1412 approved these changes
Only one very small comment. Other than that, I like the way this has been implemented. A lot of the changes are the same thing over and over, which seems to suggest maybe some code duplication could be improved in these files, but definitely out of scope for this PR. Just keep an eye out, if you do make changes, that you might need to do it many times.

2024-09-25 03:56 UTC, BadMagic100 commented
Yeah, all the code duplication is there and painful. Not really sure if there would be a better way to deal with it, as it's all "iterate and subtest each testable world" and at the very least that code duplication will always be there in every relevant test even if we did something like introduce a decorator that does it automatically (which is actually not a half-bad idea tbh)

2024-10-04 18:03 UTC, qwint requested changes
reviewed wording changes in docs files,
tested generating with a broken but soft_disabled world to see the warning
tested pytest with a broken world using all enum values, seeing the failures on enabled and hidden, and not seeing test failures on the two disabled versions
retested with unittest to see the same results

Didn't extensively review the code changes but did skim for any glaring issues
Didn't test hidden feature on webhost (although that seems mostly untouched, just set differently)

The one big issue I saw was:
Disabled worlds don't get considered in the `Exception: No world found to handle game . . .` error message, there should probably be a unique error message if a world in generation is disabled noting that.

2024-10-04 18:05 UTC, qwint commented
Also, the pytest handling seems to run before even `pytest -h` which is annoying but not end of the world

2024-11-20 20:08 UTC, Exempt-Medic commented on worlds/archipidle/__init__.py
> +    status = Status.enabled if (datetime.now().month == 4) else Status.hidden_enabled
```suggestion
    status = Status.enabled if (datetime.now().month == 4) else Status.hidden_enabled  # Only visible during April
```

2024-11-20 20:28 UTC, Exempt-Medic commented on docs/world maintainer.md
> +a mechanism to "soft disable" a world in order to allow core changes/tests to be merge which would not strictly break
```suggestion
a mechanism to "soft disable" a world in order to allow core changes/tests to be merged which would not strictly break 
```

2024-11-21 00:58 UTC, Exempt-Medic commented on BaseClasses.py
> +                                f"which is currently considered to be unstable."
Missing space
```suggestion
                                f"which is currently considered to be unstable. "
```

2024-11-28 14:53 UTC, Exempt-Medic commented
When trying this I got "OriBlindForest Assigned options through option_definitions which is now deprecated. Please use options_dataclass instead." which seems unintended

2025-01-15 03:21 UTC, BadMagic100 commented
That does seem unintentional, I guess the classvar assignments would still get to happen for disabled worl

2025-01-15 03:23 UTC, BadMagic100 commented
> Also, the pytest handling seems to run before even `pytest -h` which is annoying but not end of the world

Unfortunately the pytest handling is not really my area of expertise, @Silvris any clue if this is avoidable?

2025-01-27 20:12 UTC, BadMagic100 commented
> That does seem unintentional, I guess the classvar assignments would still get to happen for disabled worlds in this scheme (don't mind the closing and opening my mobile keyboard was too close to close with comment)

Regarding this

2025-01-27 20:14 UTC, BadMagic100 commented
> When using this I got "OriBlindForest Assigned options through option_definitions which is now deprecated. Please use options_dataclass instead." which seems unintended

After some research I believe the fix here is to just check the attr early and return None, short circuiting past any other logic which may or may not happen including during `super().__new__`

2025-01-28 18:38 UTC, BadMagic100 commented
Closing this. There is general alignment this is not the right solution to the problem.

2025-01-28 18:38 UTC, closed without merging