Timespinner: Update AP to have parity with standalone options
ArchipelagoMW/Archipelago pull request #3805
Opened 2024-08-17 00:36 UTC by Ehseezed

## What is this fixing or adding?
Adds in the `Prism Break` and `Aura Cap` options, as well as introducing the `Throw Stun Trap` item to the trap pool.
Also changed "mini jackpot" room to "jacksquat" room because of community feedback during an event.

## How was this tested?
Tested using debug `!getitem` as well as a complete test game with no issues found with the functionality.

2024-08-17 00:39 UTC, Exempt-Medic commented on worlds/timespinner/Options.py
> +    default = [ "Meteor Sparrow Trap", "Poison Trap", "Chaos Trap", "Neurotoxin Trap", "Bee Trap", 'Throw Stun Trap' ]
```suggestion
    default = [ "Meteor Sparrow Trap", "Poison Trap", "Chaos Trap", "Neurotoxin Trap", "Bee Trap", "Throw Stun Trap" ]
```

2024-08-17 09:27 UTC, Jarno458 requested changes
Add on line 226 in _init_.py
```
        elif name in {"Laser Access A", "Laser Access I", "Laser Access M"} \
                and not self.options.prism_break:
            item.classification = ItemClassification.filler
```

2024-08-17 09:27 UTC, Jarno458 commented on worlds/timespinner/__init__.py
> +            "MpCap": self.options.aura_cap.value,
this string must be `"AuraCap"` to be picked up by the client

2024-08-17 09:27 UTC, Jarno458 commented on worlds/timespinner/Options.py
> +    """Sets the number that Lunais's MP maxes out at."""
I prefer these descriptions to match the non ap version, so this should be 
`"""Sets the maximum Aura Lunais is allowed to have. Level 1 is 80. Djinn Inferno costs 45"""`

2024-08-18 14:30 UTC, Jarno458 approved these changes
LGTM, ran it through some test generations and all seems fine

2024-08-18 14:36 UTC, Exempt-Medic commented on worlds/timespinner/LogicExtensions.py
> +            return state.has_all({'Killed Maw', 'Killed Twins', 'Killed Aelana'}, self.player)
You can do this instead
```suggestion
        if self.flag_prism_break:
            return state.has_all({'Laser Access M', 'Laser Access I', 'Laser Access A'}, self.player)
        return state.has_all({'Killed Maw', 'Killed Twins', 'Killed Aelana'}, self.player)
```

2024-08-18 14:36 UTC, Exempt-Medic commented on worlds/timespinner/Options.py
> +    """Sets the maximum Aura Lunais is allowed to have. Level 1 is 80. Djinn Inferno costs 45"""
Overall it's very inconsistent in this file, but this should probably have a period
```suggestion
    """Sets the maximum Aura Lunais is allowed to have. Level 1 is 80. Djinn Inferno costs 45."""
```

2024-08-18 16:57 UTC, Exempt-Medic approved these changes
The changes look fine, and are consistent with the rest of the formatting in the files. Generations still work and the WebHost displays the new options well. I don't know the game well, but Jarno approved it so like, yeah

2024-11-29 19:45 UTC, Berserker66 approved these changes

2024-11-29 19:46 UTC, merged