The Messenger: add webhost auto connection steps to guide
ArchipelagoMW/Archipelago pull request #3904
Opened 2024-09-08 00:18 UTC by alwaysintreble

## What is this fixing or adding?
This new feature got added and The Messenger already supports it as part of the feature but i forgor to update docs.

2024-09-08 17:59 UTC, ReverM requested changes
The current steps uses the word game too much to refer to different things. It is slightly confusing

2024-09-08 17:59 UTC, ReverM commented on worlds/messenger/docs/setup_en.md
> +2. Click on your name on the left side.
Tiny nitpick, but 
```suggestion
2. Click on your slot name on the left side.
```

2024-09-08 17:59 UTC, ReverM commented on worlds/messenger/docs/setup_en.md
> +1. Go to the room page for the game you are going to join.
```suggestion
1. Go to the room page of the MultiWorld you are going to join.
```
Game is used later and is confusing

2024-09-08 17:59 UTC, ReverM commented on worlds/messenger/docs/setup_en.md
> +   before launching the game.
```suggestion
   before launching The Messenger.
```

2024-09-08 17:59 UTC, ReverM commented on worlds/messenger/docs/setup_en.md
> +5. Start a new save. You will already be connected in game and do not need to go through the menus.
```suggestion
5. Start a new save. You will already be connected in The Messenger and do not need to go through the menus.
```

2024-09-14 16:46 UTC, Exempt-Medic commented on worlds/messenger/docs/setup_en.md
> +   Steam asking if the game should be launched with arguments. These arguments are the URI with which the mod uses to
I think you can just remove this word
```suggestion
   Steam asking if the game should be launched with arguments. These arguments are the URI which the mod uses to
```

2024-09-14 16:46 UTC, Exempt-Medic approved these changes
One small comment, the rest looks good to me

2024-09-26 23:22 UTC, nicholassaylor approved these changes
You might want to italicize "The Messenger" in the docs, but otherwise the info looks great!

2024-09-26 23:25 UTC, NewSoupVi approved these changes

2024-09-26 23:25 UTC, merged