LTTP: Reduce Deprecated Calls
ArchipelagoMW/Archipelago pull request #4134
Opened 2024-11-03 15:15 UTC by nicholassaylor

Duplicate of #4129 due to renaming branch
## What is this fixing or adding?
Goes through the majority of ALTTP and updates options calls to use the appropriate access API.

A few files were skipped over for various reasons
* Rom.py was skipped due to unfamiliarity with code
* StateHelpers.py was skipped due to use of CollectionState
* Majority of Bosses.py was skipped due to use of CollectionState

An effect of this change, the log files for unittests are significantly shorter.

Could potentially merge into #3764 if that is desired, however I believe that this PR works without it

## How was this tested?
Running all unittests
Running Generate with seed=1 and comparing patch files and spoiler logs

2024-11-29 20:10 UTC, NewSoupVi commented
Looks like this will be necessary to get in sooner rather than later. Alright, will have a look at this soon.

2024-11-30 03:52 UTC, nicholassaylor commented
I believe that this PR is now in a state to properly review. The world -> multiworld changes have been moved to a branch that will be PRed after this gets looked at. PR post now accurately reflects the state of the code.

2025-01-13 23:31 UTC, NewSoupVi requested changes
Some problems found.

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +    if world.worlds[player].options.glitches_required.value in ['overworld_glitches', 'hybrid_major_glitches', 'no_logic']:
I don't think this works - The `.value` is gonna be an int, not a string.
I believe you can actually drop the `.value` here. Using `in` on a list or tuple just needs **equality** to be implemented. Only if it were a set instead of a list/tuple, there would be an issue.

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +        if world.worlds[player].options.glitches_required.value in ['hybrid_major_glitches', 'no_logic']:
Same thing here.

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +    if world.worlds[player].options.glitches_required.value in ['overworld_glitches', 'hybrid_major_glitches', 'no_logic']:
ditto

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +    if world.worlds[player].options.mode not in ['open', 'inverted'] or (world.worlds[player].options.mode == 'inverted' and world.shuffle_ganon is False):
You did it correctly here, for the record. :)

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/ItemPool.py
>                                         'ganon_pedestal'):
Would be nice to make sure the identation matches the new line.

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/ItemPool.py
> +    if world.options.timer.value not in (False, 'display', 'timed', 'timed_ohko', 'ohko', 'timed_countdown'):
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/ItemPool.py
> +    if world.options.timer.value in ['ohko', 'timed_ohko']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/ItemPool.py
> +    if world.options.goal.value in ['pedestal', 'triforce_hunt', 'local_triforce_hunt']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/ItemPool.py
> +    if world.options.goal.value in ['triforce_hunt', 'local_triforce_hunt']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rom.py
Wait why tho lol

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rom.py
Idk it's fine but am confused

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rom.py
> +    if local_world.options.shuffle_prizes.value in ("general", "both"):
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rom.py
> +    if local_world.options.shuffle_prizes.value in ("bonk", "both"):
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +    elif world.worlds[player].options.glitches_required.value in ['hybrid_major_glitches', 'no_logic']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +        if world.worlds[player].options.glitches_required.current_key in {'overworld_glitches', 'hybrid_major_glitches', 'no_logic'} and world.worlds[player].options.entrance_shuffle.current_key not
Ftr, this is the other option. You *can* perform `in` on an option and a set, but then you have to do `current_key` instead of `value`

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +    if not world.worlds[player].swamp_patch_required and world.worlds[player].options.glitches_required.value not in ['hybrid_major_glitches', 'no_logic']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +    if world.options.enemy_health.value in ("hard", "expert") or world.options.enemy_shuffle:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +    if not world.options.small_key_shuffle and world.options.glitches_required.value not in ['hybrid_major_glitches', 'no_logic']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +    if world.options.goal.value in ['ganon_triforce_hunt', 'local_ganon_triforce_hunt']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +                           and (world.worlds[player].options.enemy_health.value in ("easy", "default")
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +        if world.worlds[player].options.glitches_required.value in ['minor_glitches', 'overworld_glitches', 'hybrid_major_glitches', 'no_logic']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +                    if world.worlds[player].options.glitches_required.value in ['minor_glitches', 'overworld_glitches', 'hybrid_major_glitches', 'no_logic'] and entrance.name not in OverworldGlitchRu
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +            if world.worlds[player].options.glitches_required.value in ['minor_glitches', 'overworld_glitches', 'hybrid_major_glitches', 'no_logic'] :
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +                if world.worlds[player].options.glitches_required.value in ['minor_glitches', 'overworld_glitches', 'hybrid_major_glitches', 'no_logic'] and entrance.name in OverworldGlitchRules.get_
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/UnderworldGlitchRules.py
> +        if world.worlds[player].options.entrance_shuffle.value in ['vanilla', 'dungeons_simple', 'dungeons_full', 'dungeons_crossed']:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +        self.fix_skullwoods_exit = self.options.entrance_shuffle.value not in ['vanilla', 'simple', 'restricted', 'dungeons_simple']
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +        self.fix_palaceofdarkness_exit = self.options.entrance_shuffle.value not in ['dungeons_simple', 'vanilla', 'simple', 'restricted']
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +        self.fix_trock_exit = self.options.entrance_shuffle.value not in ['vanilla', 'simple', 'restricted', 'dungeons_simple']
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                and self.options.entrance_shuffle_seed != "random"):
Minor thing, this looks like it fits on one line now

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                    self.options.glitches_required))
Our style guide disallows this, the `)` must go on the next line.

You must either do
```py
foo = bar(
    1,
    2,
)
```

or

```py
foo = bar(1, 2,
      3, 4)
```

You can't do

```py
foo = bar(
    1,
    2)
```

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                self.options.non_local_items |= self.item_name_groups[option.item_name_group]
I'm not sure this works? OptionSet does not override `__or__`, so | shouldn't work on the instance. I think this must stay as `self.options.local_items.value`

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                self.options.local_items |= self.item_name_groups[option.item_name_group]
I'm not sure this works? OptionSet does not override __or__, so | shouldn't work on the instance. I think this must stay as self.options.local_items.value

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                    self.options.non_local_items -= {"Small Key (Hyrule Castle)"}
OptionSet also does not override `__sub__`, so - shouldn't work on the instance.

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +        if self.options.goal.value in ["local_triforce_hunt", "local_ganon_triforce_hunt"]:
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +        if (self.options.glitches_required.value not in ["no_glitches", "minor_glitches"] and
`.value` again

2025-01-13 23:31 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                self.options.entrance_shuffle.value in [
`.value` again

2025-01-13 23:38 UTC, nicholassaylor commented on worlds/alttp/Rom.py
I'm sure there was a reason at some point, but I can't remember it now.

2025-01-13 23:49 UTC, NewSoupVi commented on worlds/alttp/Rom.py
fair

2025-01-14 01:11 UTC, nicholassaylor commented on worlds/alttp/__init__.py
> +                    self.options.glitches_required))
I believe that I fixed it

2025-01-14 01:28 UTC, NewSoupVi requested changes
Discovered something else when doing test generations

2025-01-14 01:28 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +                    self.local_early_items["Small Key (Hyrule Castle)"] = 1
local_early_items is a MultiWorld attribute and not part of the options system - this actually needs to be straight up reverted

2025-01-14 01:28 UTC, NewSoupVi commented on worlds/alttp/__init__.py
> +            self.local_early_items["Small Key (Hyrule Castle)"] = 1
ditto

2025-01-14 01:29 UTC, NewSoupVi commented on worlds/alttp/Shops.py
>          if multiworld.randomize_shop_prices[player]:
MIssed

2025-01-14 08:14 UTC, NewSoupVi commented on worlds/alttp/Options.py
> +            and (world.worlds[player].options.entrance_shuffle.value in {'vanilla', 'dungeons_simple', 'dungeons_full', 'dungeons_crossed'} or not
Has to stay as current_key

2025-01-14 08:24 UTC, NewSoupVi commented on worlds/alttp/Rules.py
> +        raise NotImplementedError(f'Not implemented yet: Logic - {world.options.glitches_required}')
this should be world.worlds[player].options.glitches_required, no?

2025-01-14 08:26 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +    if world.worlds[player].options.glitches_required.value in ['overworld_glitches', 'hybrid_major_glitches', 'no_logic']:
Another `.value` that needs to be removed

2025-01-14 08:26 UTC, NewSoupVi commented on worlds/alttp/EntranceShuffle.py
> +        if world.worlds[player].options.glitches_required.value in ['hybrid_major_glitches', 'no_logic']:
Another `.value` that needs to be removed

2025-01-14 08:29 UTC, NewSoupVi commented on worlds/alttp/UnderworldGlitchRules.py
> +    if world.worlds[player].options.fix_fake_world:
This needs to be reverted - fix_fake_world is an ALTTPWorld attribute, not an option

2025-01-14 08:29 UTC, NewSoupVi commented on worlds/alttp/UnderworldGlitchRules.py
> +    if not world.worlds[player].options.swamp_patch_required:
This needs to be reverted - swamp_patch_required is an ALTTPWorld attribute, not an option

2025-01-14 08:32 UTC, NewSoupVi commented
There are a couple instances of `world.swordless[player]` that were missed.
![image](https://github.com/user-attachments/assets/2cf9ebbb-ba1c-4f4c-8adf-a7f1d4bccff3)

2025-01-14 08:35 UTC, NewSoupVi commented
In Rom.py line, an instance of `glitches_required[player]` was missed.

2025-01-14 15:07 UTC, nicholassaylor commented on worlds/alttp/Rules.py
> +        raise NotImplementedError(f'Not implemented yet: Logic - {world.options.glitches_required}')
Yes

2025-01-14 16:23 UTC, NewSoupVi commented
> In Rom.py line, an instance of world.glitches_required[player] was missed.

Wow, I was *tired* earlier, sorry for making you go look for it :D

2025-01-14 16:25 UTC, nicholassaylor commented
> > In Rom.py line, an instance of world.glitches_required[player] was missed.
> 
> Wow, I was _tired_ earlier, sorry for making you go look for it :D

I was able to piece together what you meant. It helped that it was in the screenshot.

2025-01-14 16:34 UTC, NewSoupVi approved these changes
Looked at every line to find potential errors - They were addressed
Did randomized test generations to catch more errors - They were addressed
Verified that any remaining generations crashes I ran into happen on the old version as well.

Did *not* compare outputs of successfully generating seeds, that's something another peer review could maybe do.

This is a peer review approval, not a core review approval.

2025-01-19 23:56 UTC, Exempt-Medic commented
I have not looked at the code, but I grabbed `main` and this and compared the spoiler logs of a two-player ALttP gen with fully-random yamls for seeds 1-50. Not exactly "good" testing, but they were identical outside of playthrough and traversal

2025-01-20 00:26 UTC, Exempt-Medic commented
Tested these changes with these tests which now passed:
* https://github.com/ArchipelagoMW/Archipelago/pull/3284
* https://github.com/ArchipelagoMW/Archipelago/pull/3382

2025-01-20 00:48 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +        if self.options.item_pool.value not in ["hard", "expert"]:
```suggestion
        if self.options.item_pool not in ["hard", "expert"]:
```

2025-01-20 00:51 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +                    shuffle, self.options.entrance_shuffle_seed,
Dropped a `.value`
```suggestion
                    shuffle, self.options.entrance_shuffle_seed.value,
```

2025-01-20 00:51 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +                self.er_seed = int(self.options.entrance_shuffle_seed)
```suggestion
                self.er_seed = int(self.options.entrance_shuffle_seed.value)
```

2025-01-20 00:52 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +                     'Crystal 7', 'Crystal 5', 'Crystal 6']]
Not really any reason to change this line

2025-01-20 00:54 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +            self.multiworld.local_early_items[self.player]["Small Key (Hyrule Castle)"] = 1
No reason to change this either
```suggestion
            world.local_early_items[player]["Small Key (Hyrule Castle)"] = 1
```

2025-01-20 00:55 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +                    world.options.glitches_required.current_key in {'overworld_glitches', 'hybrid_major_glitches',
I think a lot of these random formatting "fixes" are weird. They aren't needed and there are tons of similar lines that aren't being touched at all

2025-01-20 00:55 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +            elif 'triforce_hunt' in world.options.goal.current_key and (
Another changed line

2025-01-20 00:56 UTC, Exempt-Medic commented on worlds/alttp/__init__.py
> +                         slot_options}
```suggestion
            slot_data = {option_name: getattr(self.options, option_name).value for option_name in slot_options}
```

2025-01-20 00:57 UTC, Exempt-Medic commented on worlds/alttp/ItemPool.py
> +                                            'Bomb Upgrade (50)', 'Cane of Somaria', 'Cane of Byrna'] and world.options.enemy_health.value not in ['default', 'easy']):
```suggestion
                                            'Bomb Upgrade (50)', 'Cane of Somaria', 'Cane of Byrna'] and world.options.enemy_health not in ['default', 'easy']):
```

2025-01-20 01:17 UTC, nicholassaylor commented on worlds/alttp/Rules.py
> +            else state._lttp_has_key('Small Key (Ice Palace)', player, 6))) and (world.can_take_damage or state.has('Hookshot', player) or state.has('Cape', player) or state.has('Cane of Byrna', play
I can't recall at the moment, but it was likely formatting on my end that never got reverted. I can change it back if that's desired.

2025-01-20 01:18 UTC, nicholassaylor commented on worlds/alttp/Rules.py
> +                                                                                                        and state.can_reach(state.multiworld.get_region('Turtle Rock (Second Section)', player)))
I believe that this line was actually suggested by Pycharm

2025-01-20 01:20 UTC, Exempt-Medic commented on worlds/alttp/Rules.py
> +                                                                                                        and state.can_reach(state.multiworld.get_region('Turtle Rock (Second Section)', player)))
I guess it's really up to the world devs, but it is a little weird to me when the refactor includes a small number of fixes, sometimes unrelated to those changes. I would _like_ the changes made, but I'm not gonna require that

2025-01-20 01:21 UTC, nicholassaylor commented on worlds/alttp/Rules.py
> +                                                                                                        and state.can_reach(state.multiworld.get_region('Turtle Rock (Second Section)', player)))
I will go through and revert the lines you marked then

2025-01-20 01:38 UTC, nicholassaylor commented
I believe that I covered everything that was requested.

2025-01-20 01:43 UTC, Exempt-Medic approved these changes
Peer Review, I suppose. My requested changes were made, the errors I found were fixed. Compared outputs of different generations, but either did not hit the few errors I found or they were not relevant. Searched through all the changes for ".value" to see any asymmetric changes and did not find any.

2025-04-18 21:23 UTC, palex00 commented
![grafik](https://github.com/user-attachments/assets/9f744302-6b72-4afe-9f55-229b560922ea)

Berserker wanted someone to fuzz this PR.

Running 1000 on current main versus this PR, it did not provide any significant improvement or worsening.

2025-04-18 21:41 UTC, Berserker66 approved these changes

2025-04-18 21:41 UTC, merged