Core: fix deprecation warning in for utcnow()
ArchipelagoMW/Archipelago pull request #4170
Opened 2024-11-11 10:51 UTC by Berserker66

## What is this fixing or adding?
`DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  self.buildtime = datetime.datetime.utcnow()`

## How was this tested?
running setup.py build_exe on py 3.12

## If this makes graphical changes, please attach screenshots.

2024-11-15 03:07 UTC, silasary approved these changes

2024-11-27 03:30 UTC, nicholassaylor approved these changes
LGTM, this should work now that 3.8 is binned

2024-11-28 12:49 UTC, nicholassaylor requested changes

2024-11-28 12:49 UTC, nicholassaylor commented on setup.py
> +        self.buildtime = datetime.datetime.now(datetime.UTC)
```suggestion
        self.buildtime = datetime.datetime.now(datetime.timezone.UTC)
```
`datetime.UTC` was added in 3.11, this should be 3.10 compatible

2024-11-28 16:19 UTC, nicholassaylor commented on setup.py
> +        self.buildtime = datetime.datetime.now(datetime.timezone.UTC)
```suggestion
        self.buildtime = datetime.datetime.now(datetime.timezone.utc)
```
Capitalization is hard

2024-11-28 23:48 UTC, black-sliver approved these changes
```python
>>> from datetime import datetime, timezone
>>> datetime.utcnow().hour == datetime.now(timezone.utc).hour
True
```

2024-11-29 00:29 UTC, nicholassaylor approved these changes

2024-11-29 00:57 UTC, merged