SM64: ItemData
ArchipelagoMW/Archipelago pull request #4321
Opened 2024-12-02 03:00 UTC by josephwhite

## What is this fixing or adding?
Adds an ItemData class to include `ItemClassification` in the item tables, similar to other worlds.
- Simplifies `create_item`.
- Utilize base id when assigning IDs. 

## How was this tested?

- Several seed generations.
   - Item ID range
   - Move rando
- Ran Webhost.py and generated a YAML (`MoveRandomizerActions` in `Options.py`).

2024-12-02 03:03 UTC, Exempt-Medic commented on worlds/sm64ex/Items.py
> +from typing import Dict, NamedTuple, Optional
Should be able to just use `dict` since 3.8/3.9 was dropped

2024-12-03 02:01 UTC, Exempt-Medic commented on worlds/sm64ex/Items.py
> +item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
Might as well add the EoF newline now
```suggestion
item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}

```

2024-12-05 23:07 UTC, Exempt-Medic commented
It's probably fine to add them, but just letting you know that `item_descriptions` don't currently do anything

2024-12-06 01:29 UTC, josephwhite commented
> It's probably fine to add them, but just letting you know that `item_descriptions` don't currently do anything

Did I mess up the implementation or did item descriptions brake between #2409/#2508 and now?
I tried to follow the [World API](https://github.com/ArchipelagoMW/Archipelago/blob/f4b926ebbe491dc9a064b5d17bdd95051a5c6496/docs/world%20api.md?plain=1#L154C1-L154C3) and [Dark Souls III implementation](https://github.com/ArchipelagoMW/Archipelago/blob/f4b926ebbe491dc9a064b5d17bdd95051a5c6496/worlds/dark_souls_3/__init__.py#L42) and didn't see any GitHub issues regarding it.

2024-12-06 02:18 UTC, Exempt-Medic commented
> Did I mess up the implementation or did item descriptions brake between #2409/#2508 and now? I tried to follow the [World API](https://github.com/ArchipelagoMW/Archipelago/blob/f4b926ebbe491dc9a064b5d17bdd95051a5c6496/docs/world%20api.md?plain=1#L154C1-L154C3) and [Dark Souls III implementation](https://github.com/ArchipelagoMW/Archipelago/blob/f4b926ebbe491dc9a064b5d17bdd95051a5c6496/worlds/dark_souls_3/__init__.py#L42) and didn't see any GitHub issues regarding it.

When the options system was overhauled, their functionality was removed. DS3 still has them, they just don't do anything. I believe you added them correctly

2024-12-06 14:01 UTC, N00byKing requested changes
Sorry, but I don't think I'm in favor of this change. It seems to introduce a lot of redundancy for very little benefit, if at all.
Adding the item classification into the table just means that there's now another field that has to be filled in.
The existing solution with the if-else looks ugly, but to me preferable than giving the classification explicitly for every item.

2024-12-10 18:01 UTC, josephwhite commented
> The existing solution with the if-else looks ugly, but to me preferable than giving the classification explicitly for every item.

Explicitly stating classification for each item doesn't have to be necessary if the same if-else logic is ported to the item tables where the default classification of items is progressive. Code has been updated to show this change if verbosity was the main downside of this change.

> When the options system was overhauled, [item descriptions] functionality was removed. DS3 still has them, they just don't do anything. I believe you added them correctly.

💀. Removed.

2025-01-14 14:00 UTC, N00byKing approved these changes
Looks a lot better, nice

2025-03-08 16:56 UTC, Exempt-Medic approved these changes

2025-03-08 17:07 UTC, merged