Core: prepare worlds.Files for APWorldContainer
ArchipelagoMW/Archipelago pull request #4331
Opened 2024-12-03 21:23 UTC by Berserker66

## What is this fixing or adding?
Not much on its own.
APContainer is now just any AP related zip file containing an archipelago.json
APPlayerContainer is the old one, aimed at files for a particular slot/player

Follow up PR(s) can then cleanly introduce APWorldContainer with the meta data we desire inside the archipelago.json.

## How was this tested?
I ran Factorio gen once and it didn't break

2024-12-07 20:54 UTC, beauxq commented on worlds/Files.py
>      An `APContainer` that represents a patch file.
```suggestion
    An `APPlayerContainer` that represents a patch file.
```

2024-12-07 22:18 UTC, beauxq approved these changes
looked at code and tested generate and patch a game

2024-12-11 04:06 UTC, Silvris approved these changes
Did not test, but changes appear fine.

2024-12-16 09:50 UTC, silasary approved these changes
Code looks good, and successfully generated a Factorio

2024-12-17 01:34 UTC, Jouramie approved these changes
APContainers is not a system I know very well, but code LGTM.

2024-12-17 01:34 UTC, Jouramie commented on worlds/Files.py
> +    def read_contents(self, opened_zipfile: zipfile.ZipFile) -> Dict[str, Any]:
Nitpicking: Now that the minimal python version is 3.10, using `Dict` from typing is no longer required. The return type could be replaced with `dict[str, Any]`. 

Same for the return type of `get_manifest` and the various `Optional[str]` that could be replaced with `str | None`.

2024-12-17 01:34 UTC, Jouramie commented on worlds/Files.py
>              "version": container_version,
Any reason to keep the `compatible_version` and `version` here? They are already added to the manifest in `APContainer`.

2025-01-14 19:11 UTC, Berserker66 commented on worlds/Files.py
>              "version": container_version,
I fully expect the two versions to near instantly diverge, but for now it is duplicated data, so sure, I removed it.

2025-01-14 19:11 UTC, Berserker66 commented on worlds/Files.py
> +    def read_contents(self, opened_zipfile: zipfile.ZipFile) -> Dict[str, Any]:
This isn't a PR to update typing, I'd rather keep it consistent with the rest of the file for now.

2025-01-19 16:49 UTC, beauxq requested changes

2025-01-19 16:49 UTC, beauxq commented on worlds/Files.py
> +    def read_contents(self, opened_zipfile: zipfile.ZipFile) -> Dict[str, Any]:
This is something I didn't notice before.
related to https://github.com/ArchipelagoMW/Archipelago/pull/4516#discussion_r1921297275

Not only is this ambiguous to both mutate and return something, this is also a breaking change.
If this base class returns something in this method, every subclass that overrides it also needs to return the same type.
That could include apworlds that are not in this repo, as well as some in this repo.

If this changes here, it needs to change in every subclass, and we need to think about the deprecation for external apworlds.

2025-05-18 23:41 UTC, NewSoupVi approved these changes

2025-05-20 21:55 UTC, merged