Super Mario 64: Basic testing
ArchipelagoMW/Archipelago pull request #4335
Opened 2024-12-05 04:39 UTC by josephwhite

## What is this fixing or adding?

Somewhat basic test setup for Super Mario 64.
Adds 24 total tests to the repo.

## How was this tested?

- Basic tests for every `WorldTestBase`.
- Existence of Coin Star locations based on the Coin Star option.
- More filler items than Power Stars in a world with the least amount of Power Stars possible.

2025-03-10 07:23 UTC, qwint commented on worlds/sm64ex/test/test_options.py
> +            assert loc in self.world.location_names
FYI this assert in a for loop setup (that is reused a couple of times) means that when it does catch errors it will only catch the first one found and exit which may make debugging which things in the full set have problems harder by hiding patterns or just forcing you to rerun the tests to find *all* of the issues
you can either use subtest (ex. https://github.com/ArchipelagoMW/Archipelago/blob/main/worlds/messenger/test/test_logic.py#L70-L71) to force them to all run even if one failure is found,

or likely the better way for simple assert loops like this, do some set math
i.e.
```py
created = set(self.world.location_names)
needed = set(loc100Coin_table)
diff = needed - created
self.assertFalse(diff, f"error message here potentially with f{diff} if needed")
```

2025-03-10 07:23 UTC, qwint commented on worlds/sm64ex/test/__init__.py
> +    game = "Super Mario 64"
```suggestion
    game = "Super Mario 64"

```

2025-03-10 07:23 UTC, qwint commented on worlds/sm64ex/test/test_options.py
> +    options = {}
FYI default tests including fill tests and empty/all tests are being recommended to not add blindly and be thoughtful for when you actually want them run vs just need to test something else,
I'm not saying you have to disable them but it seems like you have other meaningful testing going on here and could skip the defaults without losing anything
(fyi you skip them by setting `WorldTestBase.run_default_tests = False`)

2025-03-10 07:23 UTC, qwint commented on worlds/sm64ex/test/test_options.py
> +            assert item_in_loc.player == self.world.player
this player assert isn't testing much when the tests are by default single player multiworlds

2025-05-09 03:29 UTC, josephwhite commented on worlds/sm64ex/test/test_options.py
> +            assert item_in_loc.player == self.world.player
Good to know.
I have a separate branch for testing that condition in a `MultiworldTestBase` which might not be appropriate for a _basic_ testing PR.

2025-05-09 03:43 UTC, josephwhite commented
Safe to guess this is blocked until the logic is fixed as part of #4699?
Only tests that are failing are `test_fill` from `WorldTestBase`, but I am uncertain about removing the default tests.

2025-07-29 13:08 UTC, Exempt-Medic commented
@N00byKing Please decide whether you want to close this PR, suggest changes for this PR, or approve this PR

2025-07-30 07:25 UTC, N00byKing commented
I'll try to get to it (and the other issues) on the weekend. Dont have the time right now

2025-08-01 21:26 UTC, N00byKing requested changes
Needs a small change. Because its been so long I've made it myself and did a PR on @josephwhite's branch directly (https://github.com/josephwhite/Archipelago/pull/1) so that its not that much effort.

Once that's in, I'll approve the PR

2025-08-02 06:13 UTC, N00byKing approved these changes

2026-02-08 21:58 UTC, duckboycool approved these changes
Confirmed the tests pass locally, made sure the changes to the main code didn't cause issues with the fuzzer and a test gen/connection, and a quick glance at the code looks good.

2026-03-10 19:10 UTC, Berserker66 commented on worlds/sm64ex/test/test_options.py
> +                assert loc in possible_locations
tests should avoid bare asserts and use self.assertIn, self.assertEqual etc., which for most test runners gives better logs at minimum.

2026-04-29 18:53 UTC, NewSoupVi approved these changes
I'm not sure what those unit test fails from before are about, if they still happen they need to be investigated of course before it can be merged

2026-04-29 18:59 UTC, duckboycool commented
They happened on another PR as well, but appear to be transient (I brought it up in core dev a bit ago). The actual cause is still unclear though I think.

2026-04-29 19:03 UTC, duckboycool commented
Well not transient enough I guess.

2026-05-03 20:20 UTC, NewSoupVi commented
~~Just merging main over and over hoping it eventually fixes itself somehow~~

2026-05-03 21:24 UTC, josephwhite commented
> ~Just merging main over and over hoping it eventually fixes itself somehow~

Welcome to my dev cycle for this pr.

2026-05-09 14:46 UTC, Berserker66 approved these changes

2026-05-09 14:46 UTC, merged