Docs: SC2 - Add a description of mission order and the impact of collect on a SC2 world
ArchipelagoMW/Archipelago pull request #4398
Opened 2024-12-26 15:11 UTC by neocerber

## What is this fixing or adding?
Added the following to SC2 documentation:
- Description that the order of the missions can also be randomized
- Explicit mention of AP collect and what it does. It is a recurring question in SC2 channel.
- Issue resulting from mission order progress being tied to Victory location. Mostly prevalent due to AP collect on goal. 

## How was this tested?
I used a writing assistant to check the text and hosted the website locally to make sure that the rendering was okay.

## If this makes graphical changes, please attach screenshots.
None

2025-01-06 03:46 UTC, nicholassaylor approved these changes
As someone who has passing knowledge on SC2, reading through the documentation, I believe that I could understand it all on first go.

Cannot comment on the French translation, however, the changes were made in the same spots and appear to be roughly the same, so I assume that the same changes were made on the French docs. Would need a native speaker to read though.

2025-01-23 03:57 UTC, qwint commented on worlds/sc2/docs/en_Starcraft 2.md
> +This is set when the multiworld is generated and it cannot be modified afterward.
this is false `/option collect_mode value`
<https://archipelago.gg/tutorial/Archipelago/commands/en#host-only-(on-archipelago.gg-or-in-your-server-console)>

2025-01-24 02:41 UTC, MaxTousss commented on worlds/sc2/docs/en_Starcraft 2.md
> +This is set when the multiworld is generated and it cannot be modified afterward.
The sentence was removed and replaced, after the paragraph, with a mention of that option. 
Done on both language

2025-01-24 02:46 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +This is set when the multiworld is generated and it cannot be modified afterward.
The sentence was removed and replaced, after the paragraph, with a mention of that option.
Done on both language.

(Sorry for "double" response, forgot to look at which account I was connected.)

2025-01-24 02:48 UTC, qwint approved these changes
looks good as far as my second hand knowledge of SC2 in ap goes

2025-02-12 18:48 UTC, massimilianodelliubaldini reviewed
Only reviewed the English doc, focused on a few things that could be more concise.

2025-02-12 18:48 UTC, massimilianodelliubaldini commented on worlds/sc2/docs/en_Starcraft 2.md
> +Missions that are available have their names in blue and those where all locations were collected are shown in white.
```suggestion
Available missions are in blue; missions where all locations were collected are in white.
```

2025-02-12 18:48 UTC, massimilianodelliubaldini commented on worlds/sc2/docs/en_Starcraft 2.md
> +If the mission is not available, its requirements will also be shown there.
```suggestion
Unavailable missions are in (what color?); their requirements will also be shown there.
```

2025-02-12 18:48 UTC, massimilianodelliubaldini commented on worlds/sc2/docs/en_Starcraft 2.md
> +used and how missions are shuffled.
```suggestion
used, and how missions are shuffled. 
```

Oxford comma

2025-02-13 18:52 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +used and how missions are shuffled.
Applied as suggested.

2025-02-13 18:52 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +If the mission is not available, its requirements will also be shown there.
Applied as suggested.

2025-02-13 18:53 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +Missions that are available have their names in blue and those where all locations were collected are shown in white.
Applied as suggested.

2025-02-13 19:20 UTC, massimilianodelliubaldini approved these changes
LGTM

2025-03-08 12:37 UTC, Exempt-Medic commented
Is this not waiting on @Ziktofel ?

2025-03-08 12:50 UTC, Exempt-Medic requested changes
Some small comments. I don't know French, but some of the English comments may be applicable there as well.

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +### Items and locations
You want a newline after a header; there's various versions of markdown that run into display problems when they are not used
```suggestion
### Items and locations

```

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +Unavailable missions are in grey; their requirements will also be shown there.
This doc seems to primarily use American English spellings
```suggestion
Unavailable missions are in gray; their requirements will also be shown there.
```

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +If you do not want this to happen, you should ask the person generating the multiworld to set the `Collect Permission`
Since it's in text, it's better to use quotes here
```suggestion
If you do not want this to happen, you should ask the person generating the multiworld to set the "Collect Permission" 
```

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +If the generation is not done via the website, the person that does the generation should modify the corresponding
Since the name is different, it makes sense to explicit mention it
```suggestion
If the generation is not done via the website, the person that does the generation should modify the `collect_mode` 
```

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/fr_Starcraft 2.md
> +### *Items* et *locations*
```suggestion
### *Items* et *locations*

```

2025-03-08 12:50 UTC, Exempt-Medic commented on worlds/sc2/docs/fr_Starcraft 2.md
> +### *Collect on goal completion*
Does this not translate? I don't see it used anywhere in the description, unlike the other non-translated headers. Instead there is "monde a atteint son objectif final, il collecte"

2025-03-08 13:16 UTC, neocerber commented on worlds/sc2/docs/fr_Starcraft 2.md
> +### *Collect on goal completion*
It was intentional not to translate it. My approach with French AP documentation is to keep in English terminology, options, etc. that are displayed in AP interface or YAML. The idea being that it is a pain to find something in a program that was already translated once (which is why my OS-es are always in English: easier to find solutions when needed XD).

2025-03-09 03:49 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +If you do not want this to happen, you should ask the person generating the multiworld to set the `Collect Permission`
I am not sure about that one. Since I want to refer to the specific option, I use the code typeset. I do the same in the next sentence with the `collect_mode` option. Are you proposing that I change all instances of "code-like" terms in a sentence from code typeset to quotes?

2025-03-09 03:56 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +If you do not want this to happen, you should ask the person generating the multiworld to set the `Collect Permission`
I think this one would make sense not to use the code format. Mostly because in this case it's not very code-like, but if you think it works just fine as code for "Collect Permission" that's fine by me 👍

2025-03-09 04:04 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +### Items and locations
Applied as suggested. Also, I made sure that other header had a newline.

2025-03-09 04:04 UTC, neocerber commented on worlds/sc2/docs/fr_Starcraft 2.md
> +### *Items* et *locations*
Applied as suggested. Also, I made sure that other header had a newline.

2025-03-09 04:04 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +If the generation is not done via the website, the person that does the generation should modify the corresponding
Applied as suggested.

2025-03-09 04:05 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +Unavailable missions are in grey; their requirements will also be shown there.
Applied as suggested. Also, I made sure that other instances of grey were changed to gray.

2025-03-09 17:12 UTC, Ziktofel requested changes

2025-03-09 17:12 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
Must match the options file:

```python
    option_light_grey = 10
    option_dark_green = 11
    option_brown = 12
    option_light_green = 13
    option_dark_grey = 14
    ```
Maybe the option keys should be renamed in order to match the US spelling

2025-03-09 17:17 UTC, Exempt-Medic commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
Oh, in that case just reverting back to the grey spelling seems fine for now, to keep this just a docs PR

2025-03-09 18:14 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
I do not think that it needs to match the options exactly, since this part does not use code typeset to enumerate them. If we want them to match, we would also need to convert "darkgreen" to "dark_green".

While I stated my "logic", I do not have a strong opinion either way. I will apply whatever you prefer, Ziktofel.

2025-03-09 23:36 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
Docs should match the values used by the command as it's an enumeration of possible values used by the command

2025-03-09 23:37 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
The context is `/option [option_name] [option_value]`

2025-03-10 00:15 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
gray reverted to grey.
Changed "[ligth/dark][color]" to "[ligth/dark] [color]" to better match the command options

2025-03-10 00:16 UTC, Ziktofel requested changes

2025-03-10 00:16 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, light green, dark grey, pink, rainbow, random, default
The actual correct is `darkgrey` (accepted by the command):
```
/color kerrigan darkgrey
```
works

2025-03-10 00:17 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, lightgreen, darkgray, pink, rainbow, random, default
It should match the form accepted by the command

2025-03-10 00:25 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, light green, dark grey, pink, rainbow, random, default
In the yaml, the option is named `dark_grey`. Does `darkgrey` also work with yaml or is the "_" removed by the code somewhere?

2025-03-10 00:57 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, light green, dark grey, pink, rainbow, random, default
Looks like the command uses its own list in the client's code:
```python
def _cmd_color(self, faction: str = "", color: str = "") -> None:
        """Changes the player color for a given faction."""
        player_colors = [
            "White", "Red", "Blue", "Teal",
```
These values ignore case

2025-03-10 00:58 UTC, Ziktofel commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, light green, dark grey, pink, rainbow, random, default
If you try the command and specify an invalid one, you'll get a list of possible values

2025-03-12 00:45 UTC, neocerber commented on worlds/sc2/docs/en_Starcraft 2.md
> +    brown, light green, dark grey, pink, rainbow, random, default
I changed the explicit mention of faction color to how to get the list from the client. This also make it robust to future addition in the list and sidestep the fact that the yaml and client don't use the same word. Change was made for both language

2025-03-12 20:24 UTC, Ziktofel approved these changes

2025-03-14 15:35 UTC, Exempt-Medic approved these changes

2025-03-14 15:35 UTC, merged