MLSS: Add new goal + Update basepatch to standalone equivalent
ArchipelagoMW/Archipelago pull request #4409
Opened 2024-12-30 06:52 UTC by jamesbrq

## What is this fixing or adding?
Adds a new goal, Emblem Hunt. Collect a number of emblems to unlock a different way to get to the final area of the game.
Adds many bugfixes over the coarse of a few months with an updated basepatch. Basepatch also adds mechanics related to the new goal.

## How was this tested?
Changes to basepatch tested in standalone randomizer. Generated and patched game successfully. No complaints from unsupported apworld out in the wild.

2025-01-21 19:08 UTC, qwint approved these changes
all my comments addressed

2025-01-28 02:53 UTC, qwint commented
friend tested the patch changes by playing through a seed with the new option, everything seemed good and the new goal worked as we expected

2025-02-20 01:43 UTC, eternalcode0 approved these changes
Generated about 10 playthroughs with a single MLSS game and didn't run into any errors.
Tested some settings that I used previously as well as several that use the new emblem hunt goal. Only went through the spoiler logs but didn't see any issues with the playthrough's logic.

2025-03-08 13:14 UTC, Exempt-Medic requested changes
Some small comments, looks quite good overall

2025-03-08 13:14 UTC, Exempt-Medic commented on worlds/mlss/StateLogic.py
> +from worlds.mlss.Options import Goal
Import should be relative
```suggestion
from .Options import Goal
```

2025-03-08 13:14 UTC, Exempt-Medic commented on worlds/mlss/__init__.py
> +                    freq = (0 if self.options.goal != "emblem_hunt" else self.options.emblems_amount)
Probably good to just be safe here and get the actual number
```suggestion
                    freq = (0 if self.options.goal != "emblem_hunt" else self.options.emblems_amount.value)
```

2025-03-08 13:14 UTC, Exempt-Medic commented on worlds/mlss/__init__.py
> +            logging.warning("Number of emblems required is greater than the number of emblems available. Adjusting value.")
A couple potential ideas here:
1. You could do this only if the goal is emblem hunt (totally optional)
2. You should include the player's name in the warning so the host knows who this is about
3. You could specify the number it was changed to (totally optional)
```suggestion
        if self.options.goal == "emblem_hunt":
            if self.options.emblems_amount < self.options.emblems_required:
                self.options.emblems_amount.value = self.options.emblems_required.value
                logging.warning(f"{self.player_name}'s number of emblems required is greater than the number of emblems available. "
                                f"Changing to {self.options.emblems_required.value}.")
```

2025-03-09 15:36 UTC, Exempt-Medic approved these changes

2025-03-09 15:37 UTC, merged