Minecraft 1.19
ArchipelagoMW/Archipelago pull request #623
Opened 2022-06-09 00:23 UTC by KonoTyran

Adds minecraft 1.19 advancements.

2022-06-09 00:24 UTC, KonoTyran commented
@espeon65536 would you kindly look this over for me.

2022-06-09 21:27 UTC, espeon65536 requested changes

2022-06-09 21:27 UTC, espeon65536 commented on worlds/minecraft/Rules.py
> +    set_rule(world.get_location("Birthday Song", player), lambda state: state.can_reach("The Lie", "Location", player) and state.can_reach('Pillager Outpost', 'Region', player))
Remove the Pillager Outpost logic check in favor of region placement.

2022-06-09 21:27 UTC, espeon65536 commented on worlds/minecraft/Locations.py
> +    "Birthday Song": AdvData(42107, 'Overworld'),
This advancement and the other Allay advancement should be in the Pillager Outpost region.

2022-06-11 21:22 UTC, Berserker66 approved these changes

2022-06-11 21:22 UTC, merged