New column for generic tracker
ArchipelagoMW/Archipelago pull request #78
Opened 2021-09-21 22:44 UTC by Fluffyhairedguy

Adding an order received column for the generic tracker so you can sort by it and see the most recent items received. Progressive items will have the number of the last one acquired. Handles new games where item list doesn't exist yet, and tested with multiple games.

2021-09-22 11:45 UTC, Berserker66 requested changes

2021-09-23 02:46 UTC, Fluffyhairedguy commented on WebHostLib/tracker.py
> +        if len(multisave) > 0:
Fixed, didn't realize I was trying to do the same thing as two lines above.

2021-09-23 02:47 UTC, Fluffyhairedguy commented on WebHostLib/tracker.py
> +                if key[1] == tracked_player and len(multisave['received_items'][key]) > 0:
Fixed and simplified

2021-09-23 02:47 UTC, Fluffyhairedguy commented on WebHostLib/tracker.py
> +                    for NetworkItem in multisave['received_items'][key]:
Fixed, was not intentional

2021-09-23 02:48 UTC, Fluffyhairedguy commented on WebHostLib/tracker.py
> +                        player_received_items[NetworkItem.item] = multisave['received_items'][key].index(NetworkItem) + 1
Now I learned about enumerate, it's exactly what I needed, fixed!

2021-09-23 11:48 UTC, merged