sm64ex: Course and Secret Randomizer
ArchipelagoMW/Archipelago pull request #790
Opened 2022-07-17 22:07 UTC by N00byKing

This adds an option to randomize both the normal courses as well as the secret courses throughout the game.

However, there's a problem: I keep getting fill errors for what should be totally fine seeds.
If someone could take a look that'd be great

2022-07-17 22:41 UTC, Alchav requested changes
I generated several times and the only failure I got was related to the code comment I left. If you can get one of these fill failures to occur can you provide a yaml and seed number?

2022-07-17 22:41 UTC, Alchav commented on worlds/sm64ex/Options.py
> +    option_Off = 0
need to add `alias_false = 0` so this option does not cause generation failure

2022-07-18 07:47 UTC, N00byKing commented
Generation failure only occurs when using Course and Secret Randomization.
Try Seed `81022829027716158669`, [yaml attached](https://github.com/ArchipelagoMW/Archipelago/files/9130279/yaml.zip)

2022-07-18 14:47 UTC, Alchav commented
Appears what happened here is it placed DDD at BITFS, where the access rule requires being able to reach DDD, so DDD is unreachable.

2022-07-18 16:24 UTC, N00byKing commented
THANK YOU!
This was getting extremely frustrating, but you're right on the money about the issue and 380 generations later and no issues means this was hopefully the last thing.
Sometimes you really do need a fresh set of eyes to find an issue.
Fixed this, and cleaned it up a bit as well. Ready for review

2022-07-21 16:25 UTC, Joethepic approved these changes

2022-07-24 17:08 UTC, espeon65536 commented
Have now looked at and played a game with it, seems fine to merge.

2022-07-25 16:39 UTC, Berserker66 approved these changes

2022-07-25 16:39 UTC, merged