Crypt of the NecroDancer
ArchipelagoMW/Archipelago pull request #842
Opened 2022-07-30 00:47 UTC by espeon65536

So, ND is in a little bit of a weird place. The mod works in the game, but there isn't "official" support for Lua modding yet even though the system is fully functional behind the scenes. However we're not expecting that support to be official anytime soon, so we may as well get it running since the setup will only get easier later on. 

The Lua mod can be found [here](https://github.com/espeon65536/APNecrodancer/releases) and should probably be included in the release notes once this is merged. The tutorial links to it as well. 

I'm not marking this as draft because it is ready to be merged, but I'm not expecting this to make it into 0.3.4 at all; it's way too close to the feature freeze and it hasn't been tested remotely close to enough.

2022-08-04 21:22 UTC, Jarno458 commented
Had a look at the code, seemed decent enough

2022-08-17 17:03 UTC, SoldierofOrder requested changes
I only examined the docs. Looks great! Just a handful of things I had suggestions for. :)

2022-08-17 17:03 UTC, SoldierofOrder commented on worlds/cotnd/docs/setup_en.md
> +available_characters: [Cadence, Melody, Aria, Nocturna]
Could you make it a little clearer for utter noobs what they need to do to include this line? Assume they've never heard of the .yaml file extension before.

2022-09-06 03:04 UTC, espeon65536 commented
Based on people's feedback and my own opinion, the Lua mod for the game is far too underdeveloped. I have some ideas for improvement, but this will take a significantly longer time than anticipated and will involve significant changes to the AP side (once I prove that the ideas can be done), probably long enough that this is not worth keeping open.

2022-09-06 03:04 UTC, closed without merging